# 行列論の基礎 {#matrix}

学部初年次の線形代数学で学ぶ重要項目について幾つかピックアップしたものである. 経済動学の学習に必要な項目を取り上げているが, 十分に網羅的になっている訳ではないので, 線形代数学の成書を1つ手元に置いておくのがよいと思う. 


## 行列の形

システムの振る舞いをよりよく理解するためには抽象的な線形空間論まで踏み込む必要があるが, それは次回以降に譲って, ここでは表形式に数を並べたものとして**行列 (matrix)** を捉えよう. 従って, 行列とは次のような対象である. 
$$
A=\begin{bmatrix}a_{1,1} & a_{1,2} & \cdots & a_{1,n-1} & a_{1,n}\\
a_{2,1} & a_{2,2} & \cdots & a_{2,n-1} & a_{2,n}\\
\vdots & \vdots & \ddots & \vdots & \vdots\\
a_{m-1,1} & a_{m-1,2} & \cdots & a_{m-1,n-1} & a_{m-1,n}\\
a_{m,1} & a_{m,2} & \cdots & a_{m-1,n} & a_{m,n}
\end{bmatrix}
$$

ただし, $a_{i,j}\in\mathbb{F}$, $i=1,\dots,m$, $j=1,\dots,n$. $\mathbb{F}$ は $\mathbb{R}$ または $\mathbb{C}$. 数 $a_{i,j}$ を行列の**成分**または**要素 (element, component, entry)** と呼ぶ. 混乱の恐れがない場合はコンマを外して $a_{ij}$ と書くことが多い. 成分を明らかにするための簡略表記として $A=[a_{ij}]$ といった書き方をする場合がある. また, 行列 $A$ の $(i,j)$ 成分 $a_{ij}$ を$A_{ij}$ のように書くこともある.


各	
$$
\begin{aligned}
  &\begin{bmatrix}a_{1,1} & a_{1,2} & \cdots & a_{1,n-1} & a_{1,n}\end{bmatrix}\\
  &\begin{bmatrix}a_{2,1} & a_{2,2} & \cdots & a_{2,n-1} & a_{2,n}\end{bmatrix}\\
  &\hspace{6em}\vdots\\
  &\begin{bmatrix}a_{m,1} & a_{m,2} & \cdots & a_{m,n-1} & a_{m,n}\end{bmatrix}
\end{aligned}
$$	
を行列の**行 (row)** という. 一方, 各
$$
\begin{bmatrix}a_{1,1}\\
a_{2,1}\\
\vdots\\
a_{m-1,1}\\
a_{m,1}
\end{bmatrix},\ \begin{bmatrix}a_{1,2}\\
a_{2,2}\\
\vdots\\
a_{m-1,2}\\
a_{m,2}
\end{bmatrix},\ \dots,\ \begin{bmatrix}a_{1,n}\\
a_{2,n}\\
\vdots\\
a_{m-1,n}\\
a_{m,n}
\end{bmatrix}
$$

を行列の**列 (column)** という. 上の行列$A$ は$m$個の行と$n$個の列を持つので, $m\times n$ 行列と呼ばれる. $\mathbb{F}^{m\times n}$　を $\mathbb{F}$ の値を成分にもつ $m\times n$ 行列の全体の集合と定義する. 

行列の形にまつわるいくつかの用語を確認しておこう. 

#### 正方行列 (square matrix) {-}


$m=n$ のとき, すなわち $A\in\mathbb{F}^{n\times n}$ のとき, $A$ は $n$ 次の**正方行列 (square matrix of order $n$)** であるいう. 

#### ゼロ行列 (zero matrix, null matrix) {-}

すべての成分がゼロである行列をゼロ行列という. サイズが $m\times n$ であるゼロ行列を $0_{m\times n}$ とか $O_{m\times n}$ と書く. 多くの場合にそうであるように, 混乱の恐れがない場合には $O$ とか $0$ と書く. 

#### 対角成分 (diagonal elements) {-}

正方行列 $A$ の成分 $\{a_{ij}\ |\ i,j=1,\dots,n\}$ のうち $i=j$ なる部分 $\{a_{11},\dots,a_{nn}\}$ を**対角成分 (diagonal element)**という. 対角成分の1つ上の成分 $\{a_{12},a_{23},\dots,a_{n-1,n}\}$ を**優対角成分 (superdiagonal element)**, 対角成分の1つ下の成分 $\{a_{21},a_{32},\dots,a_{n,n-1}\}$ を**劣対角成分 (subdiagonal element)** という. 対角成分の和を**トレース (trace)** といい, $\mathrm{trace}A$ と書く.

#### 三角行列 (triangular matrix) {-}

正方行列$A=[a_{ij}]$ が $i>j\Rightarrow a_{ij}=0$ を満たすとき, $A$ を**上三角行列 (upper triangular matrix)** という. 一方, $A=[a_{ij}]$ が $i<j\Rightarrow a_{ij}=0$ を満たすとき, $A$ は**下三角行列 (lower triangular matrix)** であるという. 上三角行列は対角成分より下にある成分がすべてゼロ, 下三角行列は対角成分より上にある成分がすべてゼロである. 



#### 対角行列 (diagonal matrix) {-}

対角成分を除いた成分がすべてゼロであるような正方行列を**対角行列 (diagonal matrix)**という. ときに, $\mathrm{diag}\{a_{1},\dots,a_{n}\}$ のように書いて対角成分が左上から順に $a_{1},\dots,a_{n}$ である対角行列を表すことがある. これは Matlab などで利用されている記法で, Python と Octave でも利用できる.

#### 単位行列 (identity matrix) {-}

対角成分がすべて$1$ である対角行列を単位行列という. $n$次の単位行列を $I_{n}$ と書く. 誤解の恐れがない場合は単に
$I$ と書く. Python では関数 numpy.eye(n) で $n$ 次単位行列を作る.

#### 転置行列 (transpose matrix) {-}

$A=[a_{ij}]\in\mathbb{F}^{m\times n}$ の転置行列 $A^{\top}$ とは, $(A^{\top})_{ij}=a_{ji}$,
$i=1,\dots,m$, $j=1,\dots n$ を満たす$m\times n$行列のことをいう. 


#### 共役転置行列 (conjugate transpose) {-}

$A=[a_{ij}]\in\mathbb{F}^{m\times n}$ の共役転置行列 $A^{*}$ とは, $(A^{*})_{ij}=\bar{a}_{ji}$,
$i=1,\dots,m$, $j=1,\dots n$ を満たす$m\times n$行列のことである. 実行列の共役転置行列は転置行列である.


#### 対称行列 (symmetric matrix) {-}

$A\in\mathbb{R}^{n\times n}$ が**対称行列 (symmetric matrix)**であるとは, $A^{\top}=A$ が成り立つことをいう.


#### エルミート行列 (Hermitian matrix) {-}

$A\in\mathbb{C}^{n\times n}$ がエルミート行列であるとは, $A^{*}=A$ が成り立つことをいう.


#### 列ベクトル・行ベクトル (column vector, row vector) {-}

のちに見るように行列の集合には元どうしの加法とスカラー倍が定義され, それらは望ましい性質を満たす. ゼロ元・逆元と呼ばれる特別な元の存在も自明であるので, 特定のサイズの行列全体の集合は, (のちに定義する) ベクトル空間の一例となっている. 特に
$$
  \mathbb{F}^{n\times1},\quad\mathbb{F}^{1\times n}
$$
は我々が頻繁に用いる有限次元ベクトル空間の表現となっている. 通常これらのうちいずれかを $\mathbb{F}^{n}$ と記す.
一般の $A\in\mathbb{F}^{n\times m}$ を$n$次元列ベクトル ($\mathbb{F}^{n\times1})$
を $m$ 個並べたものと捉えたり, $m$次元列ベクトル ($\mathbb{F}^{1\times m})$ を $n$
個並べたものと捉えたりすることがある.


#### ブロック行列 (block matrix) {-}

行列をいくつかの部分行列に分解した上で分析する方が都合の良い場合がある. 例えば,
$$
A=\left[
  \begin{array}{ccc|ccc}
    a_{1,1} & \cdots & a_{1,n} & a_{1,n+1} & \cdots & a_{1,n+q}\\
    \vdots & \ddots & \vdots & \vdots & \ddots & \vdots\\
    a_{m,1} & \cdots & a_{m,n} & a_{m,n+1} & \cdots & a_{m,n+q}\\
    \hline a_{m+1,1} & \cdots & a_{m+1,n} & a_{m+1,n+1} & \cdots & a_{m+1,n+q}\\
    \vdots & \ddots & \vdots & \vdots & \ddots & \vdots\\
    a_{m+p,1} & \cdots & a_{m+p,n} & a_{m+p,n+1} & \cdots & a_{m+p,n+q}
  \end{array}
  \right]
  =:
  \left[
    \begin{array}{c|c}
      A_{11} & A_{12}\\
      \hline 
      A_{21} & A_{22}
    \end{array}
  \right]
$$
のように, 大きな行列 $A\in\mathbb{F}^{(m+p)\times(n+q)}$ を4つの部分行列 $A_{11}\in\mathbb{F}^{m\times n}$,
$A_{12}\in\mathbb{F}^{m\times q}$, $A_{21}\in\mathbb{F}^{p\times n}$,
$A_{22}\in\mathbb{F}^{p\times q}$ に分解するなどである.[^colondef] $A_{12}=0$, $A_{21}=0$
であるとき, **ブロック対角行列 (block diagonal matrix)**であるといい, $A_{21}=0$ であるとき**ブロック上三角行列 (block upper triangular matrix)**であるなどという. 

[^colondef]: $P:=Q$ という表現は, $P$ を $Q$ で定義するという意味, $P =:Q$ は $Q$ 
             を$P$ で定義するという意味である.

## 行列の演算

#### スカラー倍 {-}

$A\in\mathbb{F}^{m\times n}$ に対してスカラー倍 (scalar multiplication) あるいは定数倍と呼ばれる操作が次のように定義される:
$\alpha\in\mathbb{F}$ について,
$$
\alpha A:=\begin{bmatrix}\alpha a_{1,1} & \alpha a_{1,2} & \cdots & \alpha a_{1,n-1} & \alpha a_{1,n}\\
\alpha a_{2,1} & \alpha a_{2,2} & \cdots & \alpha a_{2,n-1} & \alpha a_{2,n}\\
\vdots & \vdots & \ddots & \vdots & \vdots\\
\alpha a_{m-1,1} & \alpha a_{m-1,2} & \cdots & \alpha a_{m-1,n-1} & \alpha a_{m-1,n}\\
\alpha a_{m,1} & \alpha a_{m,2} & \cdots & \alpha a_{m-1,n} & \alpha a_{m,n}
\end{bmatrix}\in\mathbb{F}^{m\times n}.
$$


#### 和 {-}

同数の行と列を持つ2つの行列に対して次のようにして和が定義できる. $A=[a_{ij}]\in\mathbb{F}^{m\times n}$,
$B=[b_{ij}]\in\mathbb{F}^{m\times n}$ に対して, 
$$
A+B:=[a_{ij}+b_{ij}]\in\mathbb{F}^{m\times n}.
$$
すなわち, 行列の和は成分ごとに和をとった行列である. 定義から自明なことであるが, 和は交換法則と結合法則を満たす. すなわち,
任意の $A,B,C\in\mathbb{F}^{m\times n}$ について 
$$
\begin{aligned}
A+B & =B+A\\
A+(B+C) & =(A+B)+C
\end{aligned}
$$
が成り立つ. ゼロ行列 $0\in\mathbb{F}^{m\times n}$ は任意の $A\in\mathbb{F}^{m\times n}$に対して
$$
  A+O_{m\times n}=A
$$
を満たす. 

#### 積 {-}

行列 $A=[a_{ij}]\in\mathbb{F}^{m\times n}$ と $B=[b_{ij}]\in\mathbb{F}^{n\times p}$
の積 $AB\in\mathbb{F}^{m\times p}$ を次のように定義する.
$$
AB:=\left[\sum_{k=1}^{n}a_{ik}b_{kj}\right].
$$
この定義は線形写像の合成という観点から見ればごく自然なものであることが分かる. 解説は別の機会に譲ることにしよう. 

正方行列 $A,B\in\mathbb{F}^{n\times n}$ に対して, $AB$ と $BA$ の両方が定義される. しかし, それらは一般には一致しない. 例えば, 
$$
\begin{aligned}
  \begin{bmatrix}
    1 & 1\\
    0 & 1
  \end{bmatrix}
  \begin{bmatrix}
    1 & 0\\
    1 & 1
  \end{bmatrix} 
  & \neq
  \begin{bmatrix}
    1 & 0\\
    1 & 1
  \end{bmatrix}
  \begin{bmatrix}
    1 & 1\\
    0 & 1
  \end{bmatrix}
\end{aligned}
$$
である. $AB=BA$ が成り立つとき, $A$ と $B$ は可換であるという. 単位行列とゼロ行列は任意の行列と可換である.
任意の $A\in\mathbb{F}^{n\times n}$ に対して 
$$
  AI_{n}=I_{n}A=A
$$
と
$$
  AO_{n\times n}=O_{n\times n}A=O_{n\times n}
$$
が成り立つ. 

行列の積には次の性質がある. 
$$
\begin{aligned}
  (AB)C & =A(BC)\\
  A(B+C) & =AB+AC\\
  (A+B)C & =AC+BC.
\end{aligned}
$$
スカラー$\alpha$に対して, 
$$
  (\alpha A)B=A(\alpha B)=\alpha(AB).
$$

#### 逆行列 (inverse matrix) {-}

正方行列 $A\in\mathbb{F}^{n\times n}$ に対して, 
$$
  AB=BA=I_{n}
$$
なる $B\in\mathbb{F}^{n\times n}$ が存在するとき $A$ は**可逆 (invertible)** あるいは**正則 (regular)** であるという. $B$ を $A$ の**逆行列 (inverse matrix)** といい $A^{-1}$ と記す. 

```{block2, type="exercise"}
逆行列は存在すれば一意的に定まることを証明せよ.
```

```{block2, type="exercise"}
逆行列は存在すれば正則であることを証明せよ. 
```

```{block2, type="exercise"}
$A,B\in\mathbb{F}^{n\times n}$ がともに正則であるとき, $AB$ は可逆であり, $(AB)^{-1}=B^{-1}A^{-1}$ が成り立つことを示せ. 
```

#### 直交行列 (diagonal matrix) {-}

$A\in\mathbb{R}^{n\times n}$ が直交行列であるとは, $A^{\top}=A^{-1}$ が成り立つことをいう. 


#### ユニタリ行列 (unitary matrix) {-}

$A\in\mathbb{C}^{n\times n}$ がユニタリ行列であるとは, $A^{*}=A^{-1}$ が成り立つことをいう. 

## 線形方程式

行列とベクトルの組
$$
\begin{aligned}
  A & =[a_{ij}]\in\mathbb{F}^{m\times n},\\
  b & =[b_{j}]\in\mathbb{F}^{m\times1}
\end{aligned}
$$
に対して, 
$$
Ax=b
$$
を満たす $x\in\mathbb{F}^{n\times1}$ を求める問題を**線形方程式 (linear equation)**という. $Ax$ は行列$A$と列ベクトル
$x$ の積である. これは次の連立1次方程式の行列表現に外ならない. 
$$
\begin{cases}
a_{11}x_{1}+\cdots+a_{1n}x_{n}=b_{1}\\
\qquad\vdots\\
a_{m1}x_{1}+\cdots+a_{mn}x_{n}=b_{m}
\end{cases}
$$

### 線形連立方程式の変形

要点を理解するために簡単な例を用いよう. 連立方程式
\begin{equation}
  \begin{cases}
    x_{1}+x_{2}=1\\
    x_{1}-x_{2}=2
  \end{cases} (\#eq:lineq001)
\end{equation}
を行列の形式で表現すると 
\begin{equation}
  \begin{bmatrix}
    1 & 1\\
    1 & -1
  \end{bmatrix}
  \begin{bmatrix}
    x_{1}\\x_{2}
  \end{bmatrix}
  =
  \begin{bmatrix}
    1\\2
  \end{bmatrix} (\#eq:lineq002)
\end{equation}
と表すことができる. 式\@ref(eq:lineq001)と全く同じ連立方程式で, 順序だけを入れ替えたもの 
\begin{equation}
\begin{cases}
x_{1}-x_{2}=2\\
x_{1}+x_{2}=1 
\end{cases} (\#eq:lineq003)
\end{equation}
を行列表示すると, 
\begin{equation}
\begin{bmatrix}1 & -1\\
1 & 1
\end{bmatrix}\begin{bmatrix}x_{1}\\
x_{2}
\end{bmatrix}=\begin{bmatrix}2\\
1
\end{bmatrix} (\#eq:lineq004)
\end{equation}
である. 式\@ref(eq:lineq002)と式\@ref(eq:lineq004)は, 全く同じ $(x_{1},x_{2})$ が解であるという意味で同値な方程式であるが, 係数行列 $A$ と定数項 $b$ が異なっている. この他にも, 式\@ref(eq:lineq001)の第1式を定数倍した
\begin{equation}
\begin{cases}
2x_{1}-2x_{2}=4\\
x_{1}+x_{2}=1
\end{cases} (\#eq:lineq005)
\end{equation}
や, 式\@ref(eq:lineq001) の第1式を第2式に足すことで得られる 
\begin{equation}
\begin{cases}
x_{1}-x_{2}=2\\
x_{1}+x_{2}+(x_{1}-x_{2})=1+2
\end{cases} (\#eq:lineq006)
\end{equation}
も同じ解をもつはずである. 各自, 式\@ref(eq:lineq005), 式\@ref(eq:lineq006) の行列表現を確認してほしい. 

あるいは次の方程式
$$
\begin{cases}
x_{2}+x_{1}=1\\
-x_{2}+x_{1}=2
\end{cases}
$$
も全く同じ方程式を変形したものなので, その行列表示 
\begin{equation}
\begin{bmatrix}1 & 1\\
-1 & 1
\end{bmatrix}\begin{bmatrix}x_{2}\\
x_{1}
\end{bmatrix}=\begin{bmatrix}1\\
2
\end{bmatrix}(\#eq:lineq007)
\end{equation}
も, $x_{1},x_{2}$ の順序は入れ替わるが同じ解を導く. 従って, $(x_{1},x_{2})$ でなく $(x_{2},x_{1})$
の順で解を得たことさえ了解していれば, 式\@ref(eq:lineq007)と式\@ref(eq:lineq004) は本質的に同じ線形方程式である.

見かけ上異なる複数の行列が連立方程式の解という観点から見れば全て同じものになるという事実は応用上大変重要である. 連立方程式や動学方程式を分析する上では,
もっとも有利な形式に変形してから分析すれば十分なのである. 特に, あらかじめ都合のよい形式に変形されているものとして理論分析を行うこともあるので,
応用者は自らそのような形式に変形し, さらに復元できなければいけない. 

 連立方程式の求解に関していえば, 同値な変形を繰り返して
$$
\begin{cases}
  x_{1}=*\\
  x_{2}=*
\end{cases}
$$
形式を導けばよい. 行列表示すると
$$
\begin{bmatrix}
  1 & 0\\
  0 & 1
\end{bmatrix}
\begin{bmatrix}
  x_{1}\\
  x_{2}
\end{bmatrix}=\begin{bmatrix}*\\
*
\end{bmatrix}
$$
を導けばよい. 



### 行基本変形

連立方程式の変形を行列の言葉で表現してみよう. 

#### 行の交換 {-}

行列の行に対するもっとも基本的な操作は行の交換であろう. 連立方程式は順序付けされてない方程式の組であり, これに無理やり順序付けたものが先ほどの行列表示に他ならないので,
行順序の変更に対して解は不変である. 

$2\times2$ 行列の行順序の変更は行列 $\left[\begin{smallmatrix}0 & 1\\
1 & 0
\end{smallmatrix}\right]$を左から掛ける操作に対応する. 
$$
\begin{aligned}
\begin{bmatrix}0 & 1\\
1 & 0
\end{bmatrix}\begin{bmatrix}1 & 1\\
1 & -1
\end{bmatrix}\begin{bmatrix}x_{1}\\
x_{2}
\end{bmatrix} & =\begin{bmatrix}1 & -1\\
1 & 1
\end{bmatrix}\begin{bmatrix}x_{1}\\
x_{2}
\end{bmatrix}\\
\begin{bmatrix}0 & 1\\
1 & 0
\end{bmatrix}\begin{bmatrix}1\\
2
\end{bmatrix} & =\begin{bmatrix}2\\
1
\end{bmatrix}.
\end{aligned}
$$
次の関係が成り立つことに注目してほしい.
$$
\begin{bmatrix}
  0 & 1\\
  1 & 0 
\end{bmatrix}^{-1}
=
\begin{bmatrix}
  0 & 1\\
  1 & 0
\end{bmatrix}.
$$
従って, 式\@ref(eq:lineq002) と式\@ref(eq:lineq004)は正則行列 $\left[\begin{smallmatrix}0 & 1\\
1 & 0
\end{smallmatrix}\right]$ を通して互いに変形し合う. 

より一般の $m\times n$ 行列についてどのようになるか考えてみよ. 

```{block2, type="exercise"}

A$\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$行と第$j$行を入れ替えた結果が行列積
$C_{ij}^{m}A$ で表せるような行列 $C_{ij}^{m}\in\mathbb{F}^{m\times m}$ が存在する.
$C_{ij}^{m}$ の要素をかきだしなさい. 
```

#### 行全体の非ゼロ定数倍 {-}

1つの行にゼロでない定数 $u$ をかける操作も行列積を用いて表現できる. ここでも簡単な場合だけ見ておこう. 
\[
\begin{bmatrix}1 & 0\\
0 & u
\end{bmatrix}\begin{bmatrix}1 & 1\\
1 & -1
\end{bmatrix}=\begin{bmatrix}1 & 1\\
u & -u
\end{bmatrix}.
\]
次の関係が成り立つことに注目してほしい.
\[
\begin{bmatrix}1 & 0\\
0 & u
\end{bmatrix}^{-1}=\begin{bmatrix}1 & 0\\
0 & 1/u
\end{bmatrix}.
\]


```{block2, type="exercise"}
$A\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$行に一斉に非ゼロ定数
$u$ をかけた結果が行列積 $D_{i}^{m}(u)A$ で表せるような行列 $D_{i}^{m}(u)\in\mathbb{F}^{m\times m}$
が存在する. $D_{i}^{m}$ の要素をかきだしなさい. 
```

#### 行の定数倍を別の行に加える {-}

1つの行に(ゼロであってもよい)定数 $a$ をかける操作も行列積を用いて表現できる. 簡単な場合だけ見ておこう. 
\[
\begin{bmatrix}1 & a\\
0 & 1
\end{bmatrix}\begin{bmatrix}1 & 1\\
1 & -1
\end{bmatrix}=\begin{bmatrix}1+a & 1-a\\
1 & -1
\end{bmatrix}.
\]
次の関係が成り立つことに注目してほしい.
\[
\begin{bmatrix}1 & a\\
0 & 1
\end{bmatrix}^{-1}=\begin{bmatrix}1 & -a\\
0 & 1
\end{bmatrix}.
\]

一般の場合は練習問題とする. 

```{block2, type="exercise"}
$A\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$行の
$a$倍を第$j$行に加えた結果が行列積 $E_{ij}^{m}(a)A$ で表せるような行列 $E_{ij}^{m}(a)\in\mathbb{F}^{m\times m}$
が存在する. $E_{ij}^{m}(a)$ の要素をかきだしなさい. 
```


### 列基本変形

行の変形と同様に, 列の変形も定義できる. 実は上で得られた行列を「右から」かける操作が列変形に対応している. 各自確認しておいてほしい. 

```{block2, type="exercise"}
$A\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$列と第$j$列を入れ替えた行列は
$AC_{ij}^{m}$ と一致する. 
```


```{block2, type="exercise"}
$A\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$列に一斉に非ゼロ定数
$u$ をかけた結果は $AD_{i}^{m}(u)$ と一致する. 
```

```{block2, type="exercise"}
$A\in\mathbb{F}^{m\times n}$ を任意の行列とする. 行列の第$i$列の
$a$倍を第$j$列に加えた結果は $AE_{ij}^{m}(a)$ と一致する. 
```

列の変形は式\@ref(eq:lineq007)で見た「解の並び替え」を一般化したものである. 線形方程式 
$$
Ax=b
$$
は
$$
AC_{ij}^{m}\left(C_{ij}^{m}\right)^{-1}x=b
$$
と同値であるから $y=\left(C_{ij}^{m}\right)^{-1}x$ と置き換えれば
$$
AC_{ij}^{m}y=b
$$
と同値である. この変換については座標変換と関連付けて今後より詳しく学ぶことになる. 

### 初等変形

行列に行基本変形と列基本変形を繰り返して得られる操作を初等変形という. $A\in\mathbb{F}^{m\times n}$, $i=1,\dots,n_{r}$, $j=1,\dots,n_{c}$ について $P_{i}$ をいずれかの行基本変形, $Q_{j}$ をいずれかの列基本変形とすると 
$$
P=P_{n_{r}}\cdots P_{1},\quad Q=Q_{1}\cdots Q_{n_{c}}
$$
を用いて初等変形 (の結果) を
$$
PAQ
$$
と表すことができる. 

```{block2, type="exercise"}
 $P,Q$ が正則行列であることを示せ.
```


```{proposition}
任意の行列 $A\in\mathbb{F}^{m\times n}$ に対して, 適当に初等変形 $P$, $Q$ を選べば
$$
  PAQ=\left[\begin{array}{c|c}
  I_{d\times d} & O_{d\times(n-d)}\\
  \hline O_{(m-d)\times d} & O_{(m-d)\times(n-d)}
  \end{array}\right]
$$
とできる. ここで, $d$ は$P,Q$の選び方によらず$A$のみから決まる定数である. 
```


#### ランク {-}

上の $d$ を行列 $A$ の**ランク (rank)**といい, $\mathrm{rank}A$ と書く. 

一般に $\mathrm{rank}A\le\min\{m,n\}$ である. この不等式が等号で成り立つとき, $A$ は**フルランク
(full rank)** であるという. 特に, $\mathrm{rank}A=m$ のとき**行フルランク (full column
rank)**, $\mathrm{rank}A=n$ のとき**列フルランク (full row rank)**という. 


```{proposition}
行列 $A\in\mathbb{F}^{n\times n}$ が正則であることと, フルランクであることは同値である. 
```

```{proof}
$A$ がフルランクであると仮定する. すなわち

$$
  PAQ=I
$$
なる初等変形 $P$, $Q$ がある. 左から $P^{-1}$, 右から $Q^{-1}$ をかけてやれば 
\begin{equation}
  A = P^{-1}Q^{-1} (\#eq:apq)
\end{equation}
が得られる. 右辺は正則なので逆行列が存在する. すなわち $A^{-1}=QP$.

$A$ は正則であるがフルランクでないと仮定する. すなわち, $d<n$ に対して 
$$
  PAQ=\left[\begin{array}{c|c}
  I_{d\times d} & O_{d\times(n-d)}\\
  \hline O_{(m-d)\times d} & O_{(m-d)\times(n-d)}
  \end{array}\right]
$$
となる. 逆行列 $A^{-1}$ が存在するので, $PAQ$ に右から $Q^{-1}A^{-1}$ をかければ 
$$ 
PAQ(Q^{-1}A^{-1})=P
$$
を得る. $PAQ$ の形状により $P$ の $(d+1)$ 行目以下はすべてゼロにならなければならないが, このような行列を基本変形の積として表現することはできない.
従って, この等式は不合理である. よって$A$はフルランクでなければならない.
```



式\@ref(eq:apq) を少し変形すると

$$
A=P^{-1}Q^{-1}=\tilde{P}^{-1}
$$

なる行基本変形のみ (あるいは列基本変形のみ) からなる初等変形 $\tilde{P}$ が存在することが分かる. $A^{-1}=\tilde{P}$
であるから, $A$ から $I$ に至る行基本変形を $I$ に施せば逆行列を得ることができる.

## 行列式 

### 置換

有限個の自然数の集合 $\{1,2,\dots,n-1,n\}$ を並び替える方法には $n!$ 通りの方法がある. この並び替え全体の集合を
$S_n$ で表す. 例えば $\sigma'=(1,2,\dots,n-1,n)$ や $\sigma''=(n,n-1,\dots,2,1)$
などが$S_{n}$ の元である. $S_{n}$ の元を**置換 (permutation)**と呼ぶ. 置換 $\sigma\in S_{n}$ を $\{1,2,\dots,n\}$
からそれ自身への全単射と考えて, $\sigma'(1)=1$, $\sigma''(n-1)=2$ などのように書くこともできる.
この記法は置換の合成 (通常, 「積」と呼ばれる) の自然な定義を導いてくれる. すなわち
\[
(\sigma_{1}\sigma_{2})(i)=\sigma_{1}(\sigma_{2}(i)),\quad i=1,2,\dots,n.
\]
**恒等置換 (identity permutation)**とは, $\sigma_{id}(i)=i$, $i=1,\dots,n$ なる置換である. **互換 (transposition)**とは, 2つの文字を入れ替える特別な置換である.
すなわち $i\neq j$ に対して 
\[
\pi_{ij}(i)=j,\quad\pi_{ij}(j)=i,\quad\pi_{ij}(k)=k,\quad k\neq i,j.
\]
すべての置換は互換の積として表すことができる. 例えば, $\sigma=(2,3,4,1)$ とすれば
\[
(1,2,3,4)\xrightarrow{\pi_{1,2}}(2,1,3,4)\xrightarrow{\pi_{1,3}}(2,3,1,4)\xrightarrow{\pi_{1,4}}(2,3,4,1)
\]
なので, $\sigma=\pi_{1,4}\pi_{1,3}\pi_{1,2}$ となる. この分解の方法は一意的ではないが,
分解された互換の数は奇遇が不変となることが知られている. 奇数個の互換の積に分解できる置換を**奇置換 (odd permutation)**,
偶数個の互換の積に分解できる置換を**偶置換 (even permutation)** と呼ぶ. 写像 $\mathrm{sgn}:S_{n}\to\{-1,1\}$ を次のように定義できる.
$$
  \mathrm{sgn}(\sigma)=\begin{cases}
  -1 & \mbox{if }\sigma\mbox{ is odd}\\
  +1 & \mbox{if }\sigma\mbox{ is even}.
  \end{cases}
$$

### 行列式の定義

正方行列 $A=[a_{ij}]\in\mathbb{F}^{n\times n}$ に対して, **行列式 (determinant)** $\det A$ ($|A|$とも書く) を次のように定義する. 
$$
  \det A=\sum_{\sigma\in S_{n}}\mathrm{sgn}(\sigma)a_{1\sigma(1)}\cdots a_{n\sigma(n)}.
$$

```{proposition}
行列式は次の性質を持つ.

1. $\det A^{\top}=\det A$.
2. $\det C_{ij}A=-\det A$ (行の交換で符号が変わる).
3. $\det D_{i}^{n}(a)A=a\det A$ (行の$a$倍で行列式が$a$倍になる. $a=0$ でも成り立つ). 
4. $\det\left(E_{ij}^{n}(a)A\right)=\det A$ (行の$a$倍を別の行に加えても行列式は変化しない).
5. $$
      \det\left[\begin{array}{ccc}
      a_{11} & \cdots & a_{1n}\\
      a_{i1}+b_{i1} & \cdots & a_{in}+b_{in}\\
      a_{n1} & \cdots & a_{nn}
      \end{array}\right]=\det\left[\begin{array}{ccc}
      a_{11} & \cdots & a_{1n}\\
      a_{i1} & \cdots & a_{in}\\
      a_{n1} & \cdots & a_{nn}
      \end{array}\right]+\det\left[\begin{array}{ccc}
      a_{11} & \cdots & a_{1n}\\
      b_{i1} & \cdots & b_{in}\\
      a_{n1} & \cdots & a_{nn}
      \end{array}\right].
    $$
6. $\det I=1$.
7. $\det AB=\det A\det B$.

```

```{block2, type="fact"}
$A\in\mathbb{F}^{n\times n}$ が正則であるための必要十分条件は $\det A\neq0$. 
```

```{block2, type="exercise"}
上の事実を証明せよ.
```

## 固有値

複素数 $\lambda$ が正方行列 $A\in\mathbb{F}^{n\times n}$ の**固有値 (eigenvalue)**
であるとは, ゼロでない列ベクトル $v\in\mathbb{C}^{n}$ が存在して 
$$
  Av=\lambda v
$$
が成り立つことをいう. ベクトル $v$ を固有値 $\lambda$ に対応する固有ベクトル (eigenvector) という.
上の方程式を変形すると線形方程式
$$
  (\lambda I-A)v=0
$$
が得られる. この方程式がゼロでないベクトルを解に持つための必要十分条件は
$$
  \phi_{A}(\lambda)=\det(\lambda I-A)=0
$$
が成り立つことである. 

```{block2, type="exercise"}
上の事実を確認せよ. 
```

$\phi_{A}(\lambda)$ は $\lambda$ に関する $n$ 次多項式であり,
固有多項式 (characteristic polynomial) という. $\phi_{A}(\lambda)=0$ は重複度を込めて$n$ 個の解を持つので, $A$ は (重複度を込めて) $n$ 個の固有値を持つ. 
$$
  \phi_{A}(\lambda)=\lambda^{n}+c_{1}\lambda^{n-1}+\cdots+c_{n}
$$
とおけば, 
$$
  c_{1}=-\mathrm{trace}A,\qquad c_{n}=(-1)^{n}\det A
$$
である.

```{block2, type="exercise"}
上の事実を確認せよ. 
```

```{theorem}
実行列 $A\in\mathbb{R}^{n\times n}$が複素固有値 $\lambda$ を持てば, $\bar{\lambda}$ も$A$ の固有値である.
```

```{block2, type="exercise"} 
上の定理を証明せよ.
```

```{theorem}
異なる固有値 $\lambda_{1}\neq\lambda_{2}$ に対する固有ベクトル $v_{1}$, $v_{2}$ は次の性質を持つ: $\alpha_{1},\alpha_{2}\in\mathbb{C}$ に対して
$$
  \alpha_{1}v_{1}+\alpha_{2}v_{2}=0\Rightarrow\alpha_{1}=\alpha_{2}=0.
$$ 
この性質を1次独立性という. 
```

```{proof}
  1次独立性が成り立たないとする. すなわち, $\alpha_{1}\neq0\neq\alpha_{2}$ があって $\alpha_{1}v_{1}+\alpha_{2}v_{2}=0$を満すとする. このとき, 
  $$
    \alpha_{1}Av_{1}+\alpha_{2}Av_{2}=0.
  $$
  固有値の定義より
  $$
    \alpha_{1}\lambda_{1}v_{1}+\alpha_{2}\lambda_{2}v_{2}=0.
  $$
  $\lambda_{1}\neq\lambda_{2}$ より, 一方はゼロでない. 一般性を失うことなく$\lambda_{1}\neq0$ とできて,
  $$
    \alpha_{1}v_{1}+(\lambda_{2}/\lambda_{1})\alpha_{2}v_{2}=0.
  $$
  $\alpha_1 v_1 + \alpha_2 v_2 = 0$ より,
  $$
    \left[
      1 - (\lambda_{2}/\lambda_{1})
    \right] \alpha_{1}v_{1}=0.
  $$
  
  $\alpha_{1}\neq0$, $v_{1}\neq0$ なので, $\lambda_{2}/\lambda_{1}=1$
  が成り立たなければならないが,　これは異なる固有値を選んだという前提に矛盾する. 従って, 相異なる固有値に対する固有ベクトルは1次独立でなければならない. 
```









