# 行列の標準形 

前回までに固有値がすべて異なる場合の固有値問題を検討した. ここでは一般の場合と, 比較的高度な話題の導入を行う. 

## 一般固有空間への分解

### ハミルトン・ケーリーの定理

$X$ を有限次元線形空間, $f:X\to X$ を線形とする. 特定の基底に関する行列表現を $A$ としたとき, 特性多項式を

$$
\phi_{A}(z)=\det(zI-A)
$$
と定義した. 基底の取り替えによって $f$ の表現が $P^{-1}AP$ となるようにした場合, 
$$
\phi_{P^{-1}AP}(z)=\det(zI-P^{-1}AP)=\det P^{-1}\det(zI-A)\det P=\phi_{A}(z)
$$
が成り立つことに注意すると, 固有多項式は基底に依存しないことが分かる. したがって, 行列の固有値問題はその背後にある線形写像の固有値問題である.
以下では, 固有多項式を $\phi_{f}(z)$ と書く.
```{theorem, name='ハミルトン・ケーリーの定理'}
 \label{thm:HC}$X$ を有限次元線形空間, $f:X\to X$ を線形とする. このとき, 任意の $x\in X$
について $\phi_{f}(f)x=0$ が成り立つ. すなわち $f$ の任意の行列表現 $A$ について, $\phi_{f}(A)$
はゼロ行列となる. 
```

%
```{proof}
付録\ref{app:a}を参照.
```

$\dim X=n$ とすると方程式 $\phi_{f}(z)=0$ には重複度を込めて$n$ 個の解を持つ. 重複を除いた解を
$$
\{z\in\mathbb{C}\ \mid\ \phi_{f}(z)=0\}=\{\lambda_{1},\dots,\lambda_{r}\}
$$
とし, $n_{i}$ を $\lambda_{i}$, $i=1,\dots,r$ の重複度とすると, $\phi_{f}(z)$
は次のように因数分解できる.
$$
\phi_{f}(z)=(z-\lambda_{1})^{n_{1}}\cdots(z-\lambda_{r})^{n_{r}}.
$$
ハミルトン・ケーリーの定理により
$$
(f-\lambda_{1})^{n_{1}}\cdots(f-\lambda_{r})^{n_{r}}=0
$$
が成り立つ. 各 $(f-\lambda_{1})^{n_{1}},\dots,(f-\lambda_{r})^{n_{r}}$
は互いに可換であるから, 積 (合成) の順序が自由に交換できることに注意してほしい. 
```{definition}
多項式 $p(z)$, $q(z)$ が互いに素であるとは, 多項式 $\tilde{p}(z)$, $\tilde{q}(z)$,
$c(z)$ が $p(z)=\tilde{p}(z)c(z)$, $q(z)=\tilde{q}(z)c(z)$ であれば必ず
$c(z)=1$ が成り立つことをいう. 
```

```{lemma}
多項式 $p(z)$, $q(z)$ が互いに素であれば, ある多項式 $a(z)$, $b(z)$ が存在して 
$$
a(z)p(z)+b(z)q(z)=1
$$
が成り立つ. 
```

この等式をベズーの等式という. 単項イデアル整域と呼ばれる特別な環では常に成り立つ.\footnote{環とは, 和と差と積が定義されている代数構造である. 例えば, 行列の集合 $\mathbb{R}^{n\times n}$ や任意次数の多項式の集合は環
$P[z]$ である. 積の逆元は必ずしも存在しない. 例えば, $1,z\in P[z]$ に対して $1/z\not\in P[z]$
である. 除算にあたる演算は $P[z]$ について閉じていない. } 多項式全体が作る環は単項イデアル整域である. 身近な例としては整数の集合 $\mathbb{Z}$ は単項イデアル整域であり,
互いに素な整数$p,q$にもこの等式を満たす整数 $x,y$ がある. 
```{lemma}
実(複素)係数多項式 $p(z)$, $q(z)$ が互いに素であることの必要十分条件は, $\mathbb{C}$ において共通根をもたないことである. 
```

%
```{lemma}
\label{lem:5}$X$ を次のように直和分解できる. 
$$
X=\ker(f-\lambda_{1})^{n_{1}}\oplus\cdots\oplus\ker(f-\lambda_{r})^{n_{r}}.
$$
各 $\ker(f-\lambda_{i})^{n_{i}}$ は $f$ の不変部分空間であり, 一般固有空間という. それらの基底に関する
$f$ の行列表現はブロック対角行列である.
```

```{proof}
定理の前半は, 非ゼロベクトル $x$ が $(f-\lambda_{i})^{n_{i}}x_{1}=0$ と $\prod_{j\neq i}(f-\lambda_{j})^{n_{j}}x_{2}=0$
を満たす2つのベクトルの和として一意的に表現できることを示せばよい. 多項式 $p(z)=(z-\lambda_{i})^{n_{i}}$
と $q(z)=\prod_{j\neq i}(z-\lambda_{j})^{n_{j}}$ は互いに素なので, ベズー等式により多項式
$a(z)$, $b(z)$ が存在して 
$$
a(z)p(z)+b(z)q(z)=1
$$
が成立する. 任意の $x\in X$ について $a(z)p(z)x+b(z)q(z)x=x$ が成り立つので, 
$$
a(f)p(f)x+b(f)q(f)x=x
$$
を得る. ハミルトン・ケーリーの定理により
$$
a(f)p(f)x\in\ker q(f),\quad b(f)q(f)x\in\ker p(f)
$$
なので, $\ker p(f)+\ker q(f)=X$ が成り立つ. あとは, $v\in\ker p(f)\cap\ker q(f)$
なら $v=0$ であることを示せばよい. 再びハミルトン・ケーリーの定理により
\begin{align}
v & =a(f)p(f)v+b(f)q(f)v=0.
\end{align}
最後の等式は $v\in\ker p(f)\cap\ker q(f)$ を使った. 

次に, 各 $\ker(f-\lambda_{i})^{n_{i}}$ は $f$ の不変部分空間であることを示す. 実際, $x\in\ker(f-\lambda_{i})^{n_{i}}$
とすれば, $f(f-\lambda_{i})^{n_{i}}x=(f-\lambda_{i})^{n_{i}}f(x)=(f-\lambda_{i})^{n_{i}}\lambda_{i}x=\lambda_{i}(f-\lambda_{i})^{n_{i}}x=0$.
{[}16ED03{]} の結果によると, 上の様に構成した基底の下で $f$ はブロック対角行列になる. 
```

%
線形写像の固有値が定める部分空間によって $X\simeq\mathbb{F}^{n}$ を直和分解できることが分かった. 
$$
\dim X=n_{1}+\cdots+n_{r}=n
$$
だから, 固有値の代数的重複度が対応する部分空間の次元とならなければならない (証明せよ). 
```{example}
\label{ex:6}次の2つの行列
$$
I_{2}=\begin{bmatrix}1 & 0\\
0 & 1
\end{bmatrix},\quad J_{2}(1)=\begin{bmatrix}1 & 1\\
0 & 1
\end{bmatrix}
$$
について
$$
\ker(I_{2}-1)=\ker(I_{2}-1)^{2}=\mathbb{R}^{2}
$$
である一方で
$$
\ker(J_{2}(1)-1)\subsetneq\ker(J_{2}(1)-1)^{2}=\mathbb{R}^{2}
$$
である. 固有値と代数的重複度が同じでも一般固有空間の構造が同じとは限らない. \qed
```


### 最小多項式

ハミルトン・ケーリーの定理より固有多項式が $\phi_{f}(f)=0$ を満たすことを確認した. しかし, $\phi_{f}(z)$
はこの性質をもつ唯一の多項式ではない. 
```{definition}
最高次の係数が 1 であり, $m_{f}(f)=0$ を満たす多項式 $m_{f}(z)$ を最小多項式という. 
```

最小多項式は特定の行列表現に依存しないことに注意. 

```{example}
例 \ref{ex:6}の記号を用いる. $I_{2}$ と $J_{2}(1)$ の最小多項式はそれぞれ
\begin{align}
m_{I_{2}}(z) & =z-1,\\
m_{J_{2}(1)}(z) & =(z-1)^{2}.
\end{align}
\qed
```

最小多項式 $m_{f}$ は$\phi_{f}$ と共通のゼロ点をもつので, 因数分解すると
$$
m_{f}(z)=(z-\lambda_{1})^{\tilde{n}_{1}}\cdots(z-\lambda_{r})^{\tilde{n}_{r}}
$$
とできる. 自然数 $\tilde{n}_{1},\dots,\tilde{n}_{r}$ を固有値$\lambda_{1},\dots,\lambda_{r}$
の幾何的重複度とよぶ. 
```{theorem}
線形写像が対角化可能であることの必要十分条件は最小多項式が重根を持たないことである. 
```

```{proof}
$f$ が対角化可能であるとしよう. 対角成分には固有値が並ぶことから $m(z)=(z-\lambda_{1})\cdots(z-\lambda_{r})$
が $m(A)=0$ を満たす最小多項式であることを簡単に示せる. 逆に $m_{f}=(z-\lambda_{1})\cdots(z-\lambda_{r})$
であれば, ある多項式 $p_{1}(z),\dots,p_{r}(z)$ が存在して, 
$$
p_{1}(z)(z-\lambda_{1})+\cdots+p_{r}(z)(z-\lambda_{r})=1
$$
が成り立つ (これはベズー等式を拡張したものである). したがって, 
$$
\mathbb{F}^{n}=\ker(A-\lambda_{1})\oplus\cdots\oplus\ker(A-\lambda_{r}).
$$
$\ker(A-\lambda_{1}),\dots,\ker(A-\lambda_{r})$ の基底 (つまり固有ベクトル) について
$f$ を表現すれば対角行列を得る. 
```

%
補題 \ref{lem:5} を強めて次のように分解できる. 証明は同様である. 
```{theorem}
$X$ を次のように直和分解できる. 
$$
X=\ker(f-\lambda_{1})^{\tilde{n}_{1}}\oplus\cdots\oplus\ker(f-\lambda_{r})^{\tilde{n}_{r}}.
$$
```


### 一般固有空間への分解

一般固有空間の構造を定めよう. 表記の簡単のため, $\tilde{n}:=\tilde{n}_{i}$, $F:=f-\lambda_{i}$,
$M_{k}:=\ker F^{k}$とする.
$$
\mathbb{F}^{n}=M_{\tilde{n}}\supsetneq M_{\tilde{n}-1}\supsetneq\cdots\supsetneq M_{1}\supsetneq M_{0}=\{0\}
$$
に注意する. $M_{\tilde{n}_{-1}}$ の基底に $V_{\tilde{n}}=\{v_{1}^{\tilde{n}},\dots,v_{r(\tilde{n})}^{\tilde{n}}\}$
を付け加えて,\footnote{通常の集合記号 $\{v_{1}^{\tilde{n}},\dots,v_{r(\tilde{n})}^{\tilde{n}}\}$
を使っているが, 以下の議論では要素の順序が意味をもつ.} $M_{\tilde{n}}=\mathbb{F}^{n_{i}}$ の基底になるようにできる. すなわち
$$
\mathbb{F}^{n}=\mathrm{span}V_{\tilde{n}}\oplus M_{\tilde{n}-1}.
$$
このとき, $FV_{\tilde{n}}:=\{Fv_{1}^{\tilde{n}},\dots,Fv_{r(\tilde{n})}^{\tilde{n}}\}\subset M_{\tilde{n}-1}$
である. これらのベクトルは1次独立であり, 
$$
\mathrm{span}FV_{\tilde{n}}\cap M_{\tilde{n}-2}=\{0\}
$$
が成り立つ. なぜなら, 
$$
\alpha_{1}Fv_{1}^{\tilde{n}}+\cdots+\alpha_{r(\tilde{n})}Fv_{r(\tilde{n})}^{\tilde{n}}\in M_{\tilde{n}-2}
$$
とすれば, 
$$
\alpha_{1}v_{1}^{\tilde{n}}+\cdots+\alpha_{r(\tilde{n})}v_{r(\tilde{n})}^{\tilde{n}}\in M_{\tilde{n}-1}.
$$
$V_{\tilde{n}}$ の構成により, $\alpha_{1}=\cdots=\alpha_{r(\tilde{n})}=0$
となる. したがって, $M_{\tilde{n}-2}$ の基底に
$$
FV_{\tilde{n}}\cup\{v_{1}^{\tilde{n}-1},\dots,v_{r(\tilde{n}-1)}^{\tilde{n}-1}\}=:FV_{\tilde{n}}\cup V_{\tilde{n}-1}=\bigcup_{k=0}^{1}F^{1-k}V_{\tilde{n}-k}=:W_{\tilde{n}-1}
$$
を付け加えて ($V_{\tilde{n}-1}=\emptyset$ かもしれない, $0\le r(\tilde{n}-1)$),
$M_{\tilde{n}-1}$ の基底を構成できる. $FW_{\tilde{n}-1}$ の元は1次独立であり, $FW_{\tilde{n}-1}\cap M_{\tilde{n}-3}=\{0\}$
が成り立つ. したがって, $M_{\tilde{n}-3}$ の基底に, 
$$
W_{\tilde{n}-2}:=FV_{\tilde{n}-1}\cup\{v_{1}^{\tilde{n}-2},\dots,v_{r(\tilde{n}-2)}^{\tilde{n}-2}\}=:FV_{\tilde{n}-1}\cup V_{\tilde{n}-2}
$$
を付け加えて, $M_{\tilde{n}-2}$ の基底を構成できる. 同様の手続きを $(\tilde{n}-1)$ 回続けると,
$M_{1}$ の基底
$$
W_{1}:=FV_{2}\cup\{v_{1}^{1},\dots,v_{r(1)}^{1}\}=:FV_{2}\cup V_{1}
$$
を得る. このようにして得た, 
$$
V=\begin{Bmatrix}F^{\tilde{n}-1}V_{\tilde{n}} & F^{\tilde{n}-2}V_{\tilde{n}-1} & F^{\tilde{n}-3}V_{\tilde{n}-2} & \cdots & FV_{2} & V_{1}\\
\vdots & \vdots & \vdots & \ddots & V_{2}\\
F^{2}V_{\tilde{n}} & FV_{\tilde{n}-1} & V_{\tilde{n}-2}\\
FV_{\tilde{n}} & V_{\tilde{n}-1}\\
V_{\tilde{n}}
\end{Bmatrix}\label{eq:V}
$$
は$\mathbb{F}^{n}$ の基底を成す. 基底の並べ方は, 次のように縦方向にならんでいると考えよう. 
$$
V=\left\{ \begin{array}{ccccc}
F^{\bullet}V_{\tilde{n}} & F^{\bullet}V_{\tilde{n}-1} & F^{\bullet}V_{\tilde{n}-2} & \cdots & V_{1}\\
\hline 1,6 & 11,15 & 19,23 & \vdots\vdots & m-1,m\\
2,7 & 12,16 & 20,24 & \vdots\vdots\\
3,8 & 13,17 & 21,25 & \vdots\vdots\\
4,9 & 14,18 & 22,26\\
5,10
\end{array}\right\} \label{eq:V-1}
$$

```{theorem}
基底 $V$ に関する $f$ の表現行列はジョルダン標準形である. 
```

```{proof}
式 \eqref{eq:V-1} の適当な1列を $\{v_{1},\dots,v_{k}\}$ と表そう. 基底の構成方法より,
$$
(f-\lambda_{i})v_{s+1}=v_{s},\quad s=1,\dots,k-1
$$
および
$$
(f-\lambda_{i})v_{1}=0
$$
が成り立つ. $\mathrm{span}\{v_{1},\dots,v_{k}\}$ は不変部分空間を成すから, $f$ の行列表現はこの典型的な例に対する表現を対角成分に並べたブロック対角行列になる.
上の関係を整理すると, 
\begin{multline}
\begin{bmatrix}fv_{1} & fv_{2} & \cdots & fv_{k-1} & fv_{k}\end{bmatrix}\\
=\begin{bmatrix}v_{1} & v_{2} & \cdots & v_{k-1} & v_{k}\end{bmatrix}\begin{bmatrix}\lambda_{i} & 1\\
 & \lambda_{i} & 1\\
 &  & \ddots & \ddots\\
 &  &  & \lambda_{i} & 1\\
 &  &  &  & \lambda_{i}
\end{bmatrix}
\end{multline}
を得る. これはジョルダン細胞 $J_{k}(\lambda_{i})$ に他ならない. 
```


## 一般化固有値問題

固有値問題を拡張した
$$
Av=\lambda Ev,\quad v\neq0,\quad v\in\mathbb{C}^{n}
$$
を $(E,A)$ に対する一般化固有値問題という. 標準的な状態方程式 $x_{t+1}=Ax_{t}$ に対しては, 固有値問題
$Av=\lambda v$ が重要であったように, デスクリプタシステム $Ex_{t+1}=Ax_{t}$ の分析では一般化固有値問題
$Av=\lambda Ev$ が重要な役割を果たす. 一般に因果性が成り立たないデスクリプタシステムについては, 解が未来の入力に依存することがある.
一般化固有値問題はシステムを前向き成分と後ろ向き成分に直和分解するシステマティックな方法を与えてくれる. 

通常の固有値問題は, $A$ が「良い形」になるような基底を探すことを目標とした. 一般化固有値問題では, $(E,A)$ が同時に「良い形」になるような基底を探す.
1点違いを強調しておくと, 定義域と終域ではことなる基底をとる. したがって, 変換された行列は $(P^{-1}EQ,P^{-1}AQ)$
によって与えられる. このような問題を扱う場合には, ペンシルと呼ばれる多項式行列 $zE-A$ を考えると便利なことが多いので,
同じ問題が「ペンシルの正準形」の問題と呼ばれることもある. 

この節は @Lewis1984, @Lewis1986, @Katayama1999
および @Berger2012 を参考にした. 付録 B で @Berger2012 に基づく証明を述べる. 

### 一般化固有値

\label{subsec:eig}

$(E,A)$ の固有多項式を
$$
\varphi_{E,A}(z)=\det(zE-A)
$$
と定義する. 次の仮定を置く. 
\begin{assumption}
$\varphi(z)$ は恒等的にはゼロでない. このとき, $(E,A)$ はレギュラーであるという. 
\end{assumption}
$E=(e_{ij}),A=(a_{ij})\in\mathbb{R}^{2\times2}$ として固有多項式を計算してみると,
$$
\varphi_{E,A}(z)=(\det E)z^{2}-(e_{11}a_{22}+e_{22}a_{11}+e_{12}a_{21}+e_{21}a_{12})z+\det A
$$
が成り立つ. $\det E=0$ であれば, $\varphi_{E,A}(z)$ の次数は $n$ を下回る. 一般に,
$\varphi_{E,A}(z)$ が恒等的にゼロでなければ, $\varphi_{E,A}(z)=0$ は $d\le n$
個の解を持つ. これらの解を $(E,A)$ の有限固有値 (finite eigenvalues) という. 有限固有値の集合を
$\mathrm{sp}(E,A)=\{z\in\mathbb{C}\ \mid\ \varphi_{E,A}(z)=0\}$ と定義する. 

同時に, $\det E=0$ であればゼロ固有値 (重複度 $n-d$) が存在し, 
$$
Ev=0,\quad v\neq0,\quad v\in\mathbb{C}^{n}
$$
なるベクトルが存在する. これらを $(E,A)$ の無限大固有値 (infinite eigenvalue) という. 

一般化固有ベクトルの構成はジョルダン標準形のケースとほとんど同じである. 

##### 1次の有限固有ベクトル

$\lambda_{i}\in\mathrm{sp}(E,A)$ とする. 

$$
(A-\lambda_{i}E)v_{ij}^{1}=0
$$
なる非ゼロベクトル $v_{ij}^{1}$, $j=1,\dots,\eta_{i}=\dim\ker(A-\lambda_{i}E)$
を1次独立に選ぶことができる. 

##### $k$次の有限固有ベクトル

$\mathrm{span}\{v_{i1}^{1},\dots,v_{i\eta_{i}}^{1}\}$ が$\lambda_{i}$
の代数的重複度と同じ次元を持てば, $\lambda_{i}$ に対応する一般化固有空間が完成している. この場合は行列が対角化されている.
さもなくば, 各 $\lambda_{i}\in\mathrm{sp}(E,A)$ と各 $j=1,\dots,\eta_{i}$
について, 高次の一般化固有ベクトル, すなわち
$$
(A-\lambda_{i}E)v_{ij}^{k+1}=Ev_{ij}^{k},\quad k\ge1
$$
なる固有ベクトルを探す. ジョルダン標準形の理論ではまさに同じ手続きが重複固有値に対するジョルダン標準形の構造を決定するのであった.
このようにして, $\lambda_{i}$ の代数的重複度と同じ数のベクトルの組
$$
V_{i}=\begin{bmatrix}v_{i1}^{1} & \cdots & v_{i1}^{k_{i1}} & | & \cdots & \cdots & | & v_{i\eta_{i}}^{1} & \cdots & v_{i\eta_{i}}^{k_{i\eta_{i}}}\end{bmatrix}
$$
が, 1次独立になるようにできる. 

##### 表現行列

各$v_{ij}$, $j=1,\dots,\eta_{i}$ に対して定まる部分行列の表現は次のようになる.
\begin{multline}
\begin{bmatrix}Av_{ij}^{1} & Av_{ij}^{2} & \cdots & Av_{ij}^{k_{ij}-1} & Av_{ij}^{k_{ij}}\end{bmatrix}\\
=\begin{bmatrix}Ev_{ij}^{1} & Ev_{ij}^{2} & \cdots & Ev_{ij}^{k_{ij}-1} & Ev_{ij}^{k_{ij}}\end{bmatrix}\begin{bmatrix}\lambda_{i} & 1\\
 & \lambda_{i} & 1\\
 &  & \ddots & \ddots\\
 &  &  & \lambda_{i} & 1\\
 &  &  &  & \lambda_{i}
\end{bmatrix}.\label{eq:weier_a}
\end{multline}
終域の基底として, $\begin{bmatrix}Ev_{ij}^{1} & Ev_{ij}^{2} & \cdots & Ev_{ij}^{k_{ij}-1} & Ev_{ij}^{k_{ij}}\end{bmatrix}$
を取っていることに注意せよ. 

##### 1次の無限大固有ベクトル

$E$ のゼロ固有値に対応する固有ベクトルを求める. 

$$
Ev_{\infty j}^{1}=0,
$$
$v_{\infty j}^{1}\neq0$, $j=1,\dots,\eta=\dim\ker E$. 

##### $k$次の無限大固有ベクトル

非ゼロベクトルの列, $v_{\infty j}^{1},\dots,v_{\infty j}^{k_{\infty j}}$ を

$$
Ev_{\infty j}^{k+1}=Av_{\infty j}^{k},\quad k\ge1
$$
が成り立つように選ぶ. 

##### 表現行列

各$v_{\infty j}$, $j=1,\dots,\eta_{i}$ に対して定まる部分行列の表現は.
\begin{multline}
\begin{bmatrix}Ev_{\infty j}^{1} & Ev_{\infty j}^{2} & \cdots & Ev_{\infty j}^{k_{\infty j}-1} & Ev_{\infty j}^{k_{\infty j}}\end{bmatrix}\\
=\begin{bmatrix}Av_{\infty j}^{1} & Av_{\infty j}^{2} & \cdots & Av_{\infty j}^{k_{\infty j}-1} & Av_{\infty j}^{k_{\infty j}}\end{bmatrix}\begin{bmatrix}0 & 1\\
 & 0 & 1\\
 &  & \ddots & \ddots\\
 &  &  & 0 & 1\\
 &  &  &  & 0
\end{bmatrix}.\label{eq:weier_e}
\end{multline}
終域の基底として $\begin{bmatrix}Av_{\infty j}^{1} & Av_{\infty j}^{2} & \cdots & Av_{\infty j}^{k_{\infty j}-1} & Av_{\infty j}^{k_{\infty j}}\end{bmatrix}$
を取っていることに注意せよ. 
```{theorem, name='ワイエルシュトラス形式'}
\label{thm:weier}$(E,A)$ はレギュラーであるとする. このとき, 上のように得た非ゼロベクトルを並べた行列
$$
\bar{V}=[v_{ij}^{k}\ |\ v_{\infty j}^{k}],\quad\bar{W}=[Ev_{ij}^{k}\ \mid Av_{\infty j}^{k}]
$$
は正則であり, 
\begin{align}
\bar{W}^{-1}E\bar{V} & =\begin{bmatrix}I\\
 & N
\end{bmatrix},\label{eq:e}\\
\bar{W}^{-1}A\bar{V} & =\begin{bmatrix}J\\
 & I
\end{bmatrix},\label{eq:a}
\end{align}
ただし, $N$ は優対角成分にのみ 1をもつべきゼロ行列. $J$ は有限固有値を対角成分にもつジョルダン標準形行列である. 
```

```{proof}
付録を参照. 
```

デスクリプタシステムについて次の結果を得る. 
```{theorem}
$(E,A)$ をレギュラーとする. デスクリプタシステム
$$
Ex_{t+1}=Ax_{t}+Bu_{t}\label{eq:desc}
$$
を前向きのシステム方程式と, 後ろ向きのシステム方程式に分解することができる. すなわち, 適当な変数変換のもとで, 
\begin{align}
\hat{x}_{t+1}^{f} & =J\hat{x}_{t}^{f}+B^{f}u_{t},\label{eq:forward}\\
\hat{x}_{t}^{b} & =N\hat{x}_{t+1}^{b}+B^{b}u_{t}.\label{eq:backward}
\end{align}
と分解できる. 
```

```{proof}
式\eqref{eq:desc} をワイエルシュトラス形式に変換しよう. 
$$
(W^{-1}EV)(V^{-1}x_{t+1})=(W^{-1}AV)(V^{-1}x_{t})+W^{-1}Bu_{t}.
$$
$\hat{x}_{t}:=V^{-1}x_{t}$, $\hat{x}_{t}=(\hat{x}_{t}^{f},\hat{x}_{t}^{b})$,
$W^{-1}B=(B^{f},-B^{b})$ の分解を式\eqref{eq:e}, \eqref{eq:a} と適合するようにすれば
$$
\begin{bmatrix}I\\
 & N
\end{bmatrix}\begin{bmatrix}\hat{x}_{t+1}^{f}\\
\hat{x}_{t+1}^{b}
\end{bmatrix}=\begin{bmatrix}J\\
 & I
\end{bmatrix}\begin{bmatrix}\hat{x}_{t}^{f}\\
\hat{x}_{t}^{b}
\end{bmatrix}+\begin{bmatrix}B^{f}\\
-B^{b}
\end{bmatrix}u_{t}.
$$
これを整理すれば結果の式を得る. 
```

%
レギュラーなデスクリプタシステムは, $\hat{x}^{f}$ の初期条件と, $\hat{x}^{b}$ の終端条件, および
$u_{t}$ によって解軌道が一意的に定まる. これは @Luenberger1977 の結果である. 
\begin{problem}
式 \eqref{eq:forward}と\eqref{eq:backward}で表されるシステムの一般解を書き下しなさい. 
\end{problem}
%

## ハミルトン・ケーリーの定理の証明

\label{app:a}

$A$ を$n\times n$ 行列とする. $A$ の第$i$行目と第$j$行目を除いた $(n-1)\times(n-1)$
行列の行列式に $(-1)^{i+j}$ を掛けたものを$A$の $(i,j)$ 余因子といい, $\Delta_{i,j}$
と記す. 
```{block2, type='fact'}
\label{fact:7} 任意の $i=1,\dots,n$ と $j=1,\dots,n$ に対して次が成り立つ. 
$$
\begin{aligned}
\det A & =a_{i1}\Delta_{i1}+\cdots+a_{in}\Delta_{in}\\
\det A & =a_{1j}\Delta_{1j}+\cdots+a_{nj}\Delta_{nj}.
\end{aligned}
$$
```

```{proof}
練習問題とする. 
```

%
$A$ の随伴行列 (adjugate matrix) を
$$
\mathrm{adj}A=\begin{bmatrix}\Delta_{11} & \Delta_{21} & \cdots & \Delta_{n1}\\
\Delta_{12} & \Delta_{22} & \cdots & \Delta_{n2}\\
\vdots & \vdots & \ddots & \vdots\\
\Delta_{1n} & \Delta_{2n} & \cdots & \Delta_{nn}
\end{bmatrix}
$$
と定義する. このとき, 次の結果が得られる. 
```{theorem}
\label{thm:adj}任意の $A\in\mathbb{R}^{n\times n}$ に対して次が成り立つ. 
$$
A\left(\mathrm{adj}A\right)=\left(\mathrm{adj}A\right)A=\left(\det A\right)I_{n\times n}.
$$
```

```{proof}
行列積の定義より
$$
\begin{aligned}
\left[A\left(\mathrm{adj}A\right)\right]_{ij} & =\sum_{k=1}^{n}A_{ik}\left(\mathrm{adj}A\right)_{kj}\\
 & =\sum_{k=1}^{n}a_{ik}\Delta_{jk}.
\end{aligned}
$$
$i=j$ のときは事実 \ref{fact:7}より $\det A$ に一致する. $i\neq j$ としよう. $\Delta_{j1},\dots,\Delta_{jn}$
は$A$ の $j$ 行目を取り除いて作られるので, $A$ の $j$ 行目を変更してもこれらの小行列式は不変である. したがって,
$A$ の $j$ 行目を $i$行目と同じ値をもつようにしてもよい. このように作った $\tilde{A}$ は $\det\tilde{A}=0$
が成り立つ. この行列を$j$ 行目に関して展開すると, 
$$
0=\det\tilde{A}=\sum_{k=1}^{n}a_{jk}\Delta_{jk}=\sum_{k=1}^{n}a_{ik}\Delta_{jk}
$$
を得る. $\left(\mathrm{adj}A\right)A=\left(\det A\right)I_{n\times n}$
についても同様に証明できる. 
```

%
```{proof, name='定理 \ref{thm:HC} の証明'}
 定理 \ref{thm:adj} より
$$
\begin{aligned}
\det(zI-A)\cdot I & =(zI-A)\left[\mathrm{adj}(zI-A)\right]\\
 & =\left[\mathrm{adj}(zI-A)\right](zI-A)
\end{aligned}
$$
が成り立つ. $\mathrm{adj}(zI-A)$ は高々 $(n-1)$次の多項式を成分とする行列なので, $\left[\mathrm{adj}(zI-A)\right]_{ij}=\Delta_{ji}=b_{ij,0}+b_{ij,1}z+\cdots+b_{ij,n-1}z^{n-1}$
と書ける. 整理すると 
$$
\mathrm{adj}(zI-A)=B_{0}+B_{1}z+\cdots+B_{n-1}z^{n-1}.
$$
$A$ と 各 $B_{0},\dots,B_{n-1}$ が可換であることに注意しよう. 
$$
\begin{aligned}
\phi_{A}(z) & =z\left(B_{0}+B_{1}z+\cdots+B_{n-1}z^{n-1}\right)-A\left(B_{0}+B_{1}z+\cdots+B_{n-1}z^{n-1}\right)\\
 & =\left(B_{0}z+B_{1}z^{2}+\cdots+B_{n-1}z^{n}\right)-\left(B_{0}A+B_{1}Az+\cdots+B_{n-1}Az^{n-1}\right)\\
 & =-B_{0}A+\left(B_{0}-B_{1}A\right)z+\cdots+\left(B_{n-2}-B_{n-1}A\right)z^{n-1}+B_{n-1}z^{n}.
\end{aligned}
$$
ここで $z=A$ を代入すると, $\phi_{A}(A)=0$ が成り立つことが分かる. 
```

%

## ワイエルシュトラス標準形の導出

@Berger2012 (以下, {[}BIT{]})の議論に沿ってワイエルシュトラス標準形を導出しよう. 

以下で定義する部分空間列は, @Wong1974 で導入された. 極限空間がデスクリプタシステムの分析に重要な役割を果たすことが知られている.
{[}@Lewis1984{]} 
```{definition, name='Wong sequences'}
 
$$
\begin{array}{cccccccc}
\mathcal{V}_{k+1} & := & A^{-1}(E\mathcal{V}_{k}), & \quad & \mathcal{V}_{0}=\mathbb{F}^{n}, & \quad & k=1,2,\dots\\
\mathcal{W}_{\ell+1} & := & E^{-1}(A\mathcal{W}_{\ell}), & \quad & \mathcal{W}_{0}=\{0\}, & \quad & \ell=1,2,\dots
\end{array}
$$
```

```{block2, type='fact'}
ウォン列は単調列であり, 有限ステップで収束する. すなわち, ある $k^{*}$, $\ell^{*}$ が存在して, 
$$
\begin{array}{ccccccccccc}
\mathcal{V}_{0} & \supsetneq & \mathcal{V}_{1} & \supsetneq & \cdots & \supsetneq & \mathcal{V}_{k} & \to & \mathcal{V}_{k^{*}} & =: & \mathcal{V}^{*}\\
\mathcal{W}_{0} & \subsetneq & \mathcal{W}_{1} & \subsetneq & \cdots & \subsetneq & \mathcal{W}_{\ell} & \to & \mathcal{W}_{\ell^{*}} & =: & \mathcal{W}^{*}
\end{array}
$$
が成り立つ. また, 
$$
\begin{array}{ccc}
\mathcal{V}^{*} & = & A^{-1}(E\mathcal{V}^{*})\\
\mathcal{W}^{*} & = & E^{-1}(A\mathcal{W}^{*})
\end{array}
$$
および, その帰結として
$$
\begin{array}{ccc}
A\mathcal{V}^{*} & \subset & E\mathcal{V}^{*}\\
E\mathcal{W}^{*} & \subset & A\mathcal{W}^{*}
\end{array}
$$
が成り立つ. 
```

```{proof}
$\mathbb{F}^{n}=\mathcal{V}_{0}\supset\mathcal{V}_{1}$ は明らか. $\mathcal{V}_{k-1}\supset\mathcal{V}_{k}$
が成り立つとすれば, 
$$
\begin{aligned}
v\in\mathcal{V}_{k+1} & \Longrightarrow Av\in E\mathcal{V}_{k}\\
 & \Longrightarrow\exists w\in\mathcal{V}_{k}\ \text{s.t.}\ Av=Ew\\
 & \Longrightarrow\exists w\in\mathcal{V}_{k-1}\ \text{s.t.}\ Av=Ew\\
 & \Longrightarrow Av\in E\mathcal{V}_{k-1}\\
 & \Longrightarrow v\in A^{-1}(E\mathcal{V}_{k-1})=\mathcal{V}_{k}.
\end{aligned}
$$
数学的帰納法により, 任意の $k$ について $\mathcal{V}_{k}\supset\mathcal{V}_{k+1}$
が成り立つ. 同様に, $\mathcal{W}_{k}\subset\mathcal{W}_{k+1}$ も証明できる. 
```

%
```{definition}
$\mathcal{V}^{*}$ を初期値部分空間 (initial manifold), $\mathcal{W}^{*}$
を終端値部分空間 (final manifold) とよぶ. 
```

```{lemma, name='{Lemma 2.3, {[}BIT{]}}'}
$(E,A)$ をレギュラーとする. このとき, 任意の $\lambda\in\mathbb{F}\setminus\mathrm{sp}(E,A)$
と $i=1,2,\dots$ に対して, 
\begin{align}
\mathcal{V}_{k} & =\mathrm{im}\left((A-\lambda E)^{-1}E\right)^{k}\label{eq:vs}\\
\mathcal{W}_{k} & =\ker\left((A-\lambda E)^{-1}E\right)^{k}\label{eq:ws}
\end{align}
が成り立つ. 特に, 
$$
\dim\mathcal{V}_{k}+\dim\mathcal{W}_{k}=n.
$$
```

```{proof}
$\lambda\in\mathbb{F}\setminus\mathrm{sp}(E,A)$ を固定する. 記号の簡単化のため
$\hat{E}:=(A-\lambda E)^{-1}E$ と記す.

まず, \eqref{eq:vs} を帰納法で示す. $k=0$ のとき, 
$$
\mathcal{V}_{0}=\mathbb{F}^{n}=\mathrm{im}\hat{E}^{0}
$$
は自明である. $\mathcal{V}_{k}=\mathrm{im}\hat{E}^{k}$ が成り立つとしよう. $\mathcal{V}_{k+1}\subset\mathrm{im}\hat{E}^{k+1}$
と $\mathcal{V}_{k+1}\supset\mathrm{im}\hat{E}^{k+1}$ を示せばよい.

{[}$\mathcal{V}_{k+1}\subset\mathrm{im}\hat{E}^{k+1}${]} $v\in\mathcal{V}_{k+1}$
とする. $w\in\mathcal{V}_{k}$ を $Av=Ew$ が成り立つように選ぶ. 
$$
(A-\lambda E)v=E(w-\lambda v)
$$
であるから, 
$$
\begin{aligned}
v & =(A-\lambda E)^{-1}E(w-\lambda v)=\hat{E}(w-\lambda v)\in\mathrm{im}\hat{E}^{k+1}.
\end{aligned}
$$

{[}$\mathcal{V}_{k+1}\supset\mathrm{im}\hat{E}^{k+1}${]} $v\in\mathrm{im}\hat{E}^{k+1}$
としよう. ある $w\in\mathrm{im}\hat{E}^{k}$ が存在して, $v=\hat{E}w=(A-\lambda E)^{-1}Ew$
が成り立つ. したがって, 
$$
Av=E(w+\lambda v).
$$
$w+\lambda v\in\mathcal{V}_{k}$ だから, $v\in\mathcal{V}_{k+1}$ がしたがう. 

次に \eqref{eq:ws} を帰納法で示す. $k=0$ のとき, $\mathcal{W}_{0}=\{0\}=\ker\left((A-\lambda E)^{-1}E\right)^{0}$
が成り立つ. $\mathcal{W}_{k}=\ker\hat{E}^{k}$ が成り立つとしよう. 

{[}$\mathcal{W}_{k+1}\subset\ker\hat{E}^{k+1}${]} $v\in\mathcal{W}_{k+1}$
とする. $Ev=Aw$ なる $w\in\mathcal{W}_{k}$ が存在する. 
$$
\begin{aligned}
(A-\lambda E)w & =E(v-\lambda w)\\
w & =\hat{E}(v-\lambda w)\\
\hat{E}v= & w+\lambda\hat{E}w\in\ker\hat{E}^{k}.
\end{aligned}
$$
したがって, $v\in\ker\hat{E}^{k+1}$. 

{[}$\mathcal{W}_{k+1}\supset\ker\hat{E}^{k+1}${]} $v\in\ker\hat{E}^{k+1}$
としよう. 
$$
\hat{E}^{k}\left(\hat{E}v\right)=0,
$$
$w=\hat{E}v$ とすれば, $w\in\ker\hat{E}^{k}=\mathcal{W}_{k}\subset\mathcal{W}_{k+1}$.
$$
(A-\lambda E)w=Ev
$$
したがって, $E(v+\lambda w)=Aw$, 定義により $v+\lambda w\in\mathcal{W}_{k+1}$.
$\lambda w\in\mathcal{W}_{k+1}$ より, $v\in\mathcal{W}_{k+1}$.
```

%
```{theorem, name='{Proposition 2.4, {[}BIT{]}}'}
\label{thm:22}$(E,A)$ をレギュラーとする. 

1. $k^{*}=\ell^{*}$,
1. $\mathcal{V}^{*}\oplus\mathcal{W}^{*}=\mathbb{F}^{n}$,
1. $\ker E\cap\mathcal{V}^{*}=\{0\}$, $\ker A\cap\mathcal{W}^{*}=\{0\}$,
and $\ker E\cap\ker A=\{0\}$. 

```

```{proof}
練習問題とする. 
```

準ワイエルシュトラス形式と呼ばれる次の正準形が得られる. 
```{theorem, name='{Theorem 2.6, {[}BIT{]}}'}
\label{thm:quasi} $(E,A)$ をレギュラーとする. $n_{1}:=\dim\mathcal{V}^{*}$,
$n_{2}:=\dim\mathcal{W}^{*}$ とし, 行列 $V\in\mathbb{F}^{n\times n_{1}}$,
$W\in\mathbb{F}^{n\times n_{1}}$ を
$$
\begin{aligned}
\mathcal{V}^{*} & =\mathrm{im}V,\qquad\mathcal{W}^{*}=\mathrm{im}W
\end{aligned}
$$
が成り立つように選ぶ. このとき, $[V\ W]$ および $[EV\ AW]$ は正則であり, $J\in\mathbb{F}^{n_{1}\times n_{1}}$
と $N\in\mathbb{F}^{n_{2}\times n_{2}}$ に対して
\begin{align}
[EV\ AW]^{-1}E[V\ W] & =\begin{bmatrix}I_{n_{1}}\\
 & N
\end{bmatrix},\label{eq:quasi0}\\{}
[EV\ AW]^{-1}A[V\ W] & =\begin{bmatrix}J\\
 & I_{n_{2}}
\end{bmatrix}\label{eq:quasi}
\end{align}
が成り立つ. さらに, $\tilde{N}$ はべきゼロ行列であり, $N^{k^{*}}=0$ が成り立つ. 
```

%
```{block2, type='remark'}
\eqref{eq:quasi0}, \eqref{eq:quasi} は
$$
AV=EVJ,\quad EW=AWN
$$
と同値であることが容易に確認できる. 
```

```{proof}
$[V\ W]$ が正則であることは, $\mathcal{V}^{*}=\mathrm{im}V$ と $\mathcal{W}^{*}=\mathrm{im}W$
および $\mathcal{V}^{*}\oplus\mathcal{W}^{*}=\mathbb{F}^{n}$ より直接従う.
$[EV\ AW]$ の正則性を示す. ある$\xi_{1}\in\mathbb{F}^{n_{1}}$, $\xi_{2}\in\mathbb{F}^{n_{2}}$
に対して
$$
\begin{bmatrix}EV & AW\end{bmatrix}\begin{bmatrix}\xi_{1}\\
\xi_{2}
\end{bmatrix}=0
$$
が成り立つとしよう. $V\xi_{1}\in\mathcal{V}^{*}\cap\ker E$ と $W\xi_{2}\in\mathcal{W}^{*}\cap\ker A$
および定理\ref{thm:22} (3) より, 
$$
\begin{bmatrix}V & W\end{bmatrix}\begin{bmatrix}\xi_{1}\\
\xi_{2}
\end{bmatrix}=0.
$$
$[V\ W]$ は正則なので, $\xi_{1}=0$, $\xi_{2}=0$ が従う. $[V\ W]$ および $[EV\ AW]$
がともに $\mathbb{F}^{n}$ の基底であるから, 定義域の基底を $[V\ W]$, 終域の基底を $[EV\ AW]$
に取り替えたときの行列表現は, ブロック対角行列になっているはずである. すなわち, 
$$
\begin{aligned}
A[V\ W] & =[EV\ AW]\begin{bmatrix}J\\
 & I_{n_{2}}
\end{bmatrix}\\
E[V\ W] & =[EV\ AW]\begin{bmatrix}I_{n_{1}}\\
 & N
\end{bmatrix}
\end{aligned}
$$
なる $J$ および $N$ が存在する. 

あとは, $N$ がべきゼロであることを示せばよい. 実は, 
$$
\mathrm{im}WN^{k}\subset\mathcal{W}_{k^{*}-k},\quad k=0,1,\dots,k^{*}\label{eq:wnk}
$$
 が成り立つ. これを示すことができれば, $\mathrm{im}WN^{k^{*}}\subset\mathcal{W}_{0}=\{0\}$
が成り立つ. $W$ は列フルランクなので単射, したがって $N^{k^{*}}=0$ が従う. 式 \eqref{eq:wnk}
を帰納法で示そう. $k=0$ に対しては, $\mathrm{im}WN^{0}=\mathrm{im}W=\mathcal{W}^{*}$
より明らか. $k=s$ で 
$$
\mathrm{im}WN^{s}\subset\mathcal{W}_{k^{*}-s}
$$
が成り立つとしよう. 
$$
\begin{aligned}
y\in\mathrm{im}WN^{s+1} & \Longrightarrow\exists x\ \text{s.t.}\ y=WN^{s+1}x\\
 & \Longrightarrow\exists x\ \text{s.t.}\ Ay=AWN\cdot N^{s}x\\
 & \Longrightarrow\exists x\ \text{s.t.}\ Ay=EW\cdot N^{s}x &  & (AWN=EW)\\
 & \Longrightarrow Ay\in E\mathcal{W}_{k^{*}-s}\\
 & \Longrightarrow Ay\in A\mathcal{W}_{k^{*}-s-1} &  & (E\mathcal{W}_{k+1}\subset A\mathcal{W}_{k})\\
 & \Longrightarrow y\in\mathcal{W}_{k^{*}-s-1}
\end{aligned}
$$
最後のステップは次のように証明できる. 今, $\bar{y}\not\in\mathrm{im}WN^{s+1}\setminus\mathcal{W}_{k^{*}-s-1}$
が存在して, $Ay=A\bar{y}\in A\mathcal{W}_{k^{*}-s-1}$ が成り立つとしよう. $y-\bar{y}\in\ker A\cap\mathrm{im}WN^{s+1}$
でなければならないが, $\mathrm{im}WN^{s+1}\subset\mathrm{im}W=\mathcal{W}^{*}$
および, $\ker A\cap\mathcal{W}^{*}=\{0\}$ であったので, $\bar{y}=y$ が成り立たなければならない.
したがって, 上のような $\bar{y}$ を選ぶことはできない. よって, $\mathrm{im}WN^{s+1}\subset\mathcal{W}_{k^{*}-s-1}$が成り立つ. 
```

```{definition, name='一般化固有空間'}
 $\lambda\in\mathrm{sp}(E,A)\cup\{\infty\}$ に対して固有空間列 $\mathcal{G}_{\lambda}^{1},\mathcal{G}_{\lambda}^{2},\dots$
を次のように定義する. まず, 
$$
\begin{aligned}
\mathcal{G}_{\lambda}^{0}: & =\{0\},\\
\mathcal{G}_{\lambda}^{k+1} & :=\begin{cases}
(A-\lambda E)^{-1}\left(E\mathcal{G}_{\lambda}^{k}\right) & \text{if}\ \lambda\in\mathrm{sp}(E,A)\\
E^{-1}\left(A\mathcal{G}_{\lambda}^{k}\right) & \text{if}\ \lambda=\infty.
\end{cases}
\end{aligned}
$$
ペンシル $(E,A)$ の $\lambda$ に対応する一般化固有空間を
$$
\mathcal{G}_{\lambda}=\bigcup_{k=1}^{\infty}\mathcal{G}_{\lambda}^{k}
$$
と定義する. 
```

%
```{block2, type='remark'}
代数的重複度, 幾何的重複度など通常の固有値問題と同様に定義する. 固有多項式
$$
\varphi_{E,A}(z)=\prod_{\lambda\in\mathrm{spec}(E,A)}(z-\lambda)^{n_{\lambda}}
$$
の各因数にかかる指数が有限固有値の代数的重複度であり, 次のように書く. 
$$
\mathrm{am}(\lambda):=n_{\lambda},\qquad\lambda\in\mathrm{spec}(E,A).
$$
無限大固有値の代数的重複度は, 
$$
\mathrm{am}(\infty):=n-\sum_{\lambda\in\mathrm{spec}(E,A)}n_{\lambda}=n-d.
$$
最後に, 
$$
\begin{aligned}
\mathrm{gm}(\lambda) & :=\dim\mathcal{G}_{\lambda}^{1},\qquad\lambda\in\mathrm{spec}(E,A)\cup\{\infty\}
\end{aligned}
$$
を幾何的重複度と呼ぶ.
```

%
```{lemma}
\label{lem:tow}各固有値 $\lambda\in\mathrm{sp}(E,A)\cup\{\infty\}$ に対して,
ある $p(\lambda)\in\mathbb{N}$ が存在して, 
$$
\mathcal{G}_{\lambda}^{0}\subsetneq\mathcal{G}_{\lambda}^{1}\subsetneq\mathcal{G}_{\lambda}^{2}\subsetneq\cdots\subsetneq\mathcal{G}_{\lambda}^{p(\lambda)}=\mathcal{G}_{\lambda}^{p(\lambda)+1}
$$
が成り立つ. 
```

```{proof}
拡大列が有限であることは, 有限次元空間の部分空間であることから明らか. 包含関係を示そう. 
$$
\mathcal{G}_{\lambda}^{k-1}\subset\mathcal{G}_{\lambda}^{k},\quad k\in\mathbb{N}
$$
を数学的帰納法によって示す. $k=0$ のときは明らか. $k=s$ で成り立つとしよう. まず, $\lambda\in\mathrm{sp}(E,A)$
の場合,
$$
\begin{aligned}
v\in\mathcal{G}_{\lambda}^{s} & \Longrightarrow v\in(A-\lambda E)^{-1}\left(E\mathcal{G}_{\lambda}^{s-1}\right)\\
 & \Longrightarrow(A-\lambda E)v\in E\mathcal{G}_{\lambda}^{s-1}\\
 & \Longrightarrow(A-\lambda E)v\in E\mathcal{G}_{\lambda}^{s}\\
 & \Longrightarrow v\in(A-\lambda E)^{-1}\left(E\mathcal{G}_{\lambda}^{s}\right)\\
 & \Longrightarrow v\in\mathcal{G}_{\lambda}^{s+1}.
\end{aligned}
$$
$\lambda=\infty$ の場合も同様に示すことができる. 
```

%
本編で用いた表現との対応について確認しておこう. $\{\lambda_{1},\dots,\lambda_{r}\}=\mathrm{sp}(E,A)$
とする. まず, 各 $i=1,\dots,r$ に対して1次独立なベクトル
$$
v_{i1}^{1},\cdots,v_{i\eta_{i}}^{1}
$$
を
$$
(A-\lambda E)v_{ij}^{1}=0,\qquad j=1,\dots,\eta_{i}\label{eq:g1}
$$
となるように選んだ. $\mathcal{G}_{\lambda_{i}}^{1}=(A-\lambda E)^{-1}\left(E\mathcal{G}_{\lambda_{i}}^{0}\right)=(A-\lambda E)^{-1}(\{0\})=\ker(A-\lambda E)$
だから, \eqref{eq:g1} は
$$
v_{ij}^{1}\in\mathcal{G}_{\lambda_{i}}^{1},\qquad j=1,\dots,\eta_{i}
$$
と同値である. 次のステップでは, 
$$
(A-\lambda E)v_{ij}^{2}=Ev_{ij}^{1},\qquad j=1,\dots,\eta_{i}
$$
なる, $v_{ij}^{2}$ を探した. これはもちろん
$$
v_{ij}^{2}\in\mathcal{G}_{\lambda_{i}}^{2},\qquad j=1,\dots,\eta_{i}
$$
である. 同様の手続きで,
$$
v_{ij}^{k}\in\mathcal{G}_{\lambda_{i}}^{k},\qquad j=1,\dots,\eta_{i},\ k=1,\dots,k_{ij}
$$
を見つけるのが, 本編で述べたアルゴリズムの骨子である. 各 $i$ と $j$ についてこの手続は有限で終了するのは, 補題
\ref{lem:tow} により $p(\lambda_{i})$ が存在することの帰結である. つまり, $k_{ij}\le p(\lambda_{i})$
が成り立つ. 容易に確かめられるように無限大固有値 $\lambda=\infty$ のときも同様である. 

このようにして得られたベクトル列 $(v_{ij}^{1},v_{ij}^{2},\dots,v_{ij}^{k})$, $k\leq k_{ij}$,
を固有値 $\lambda_{i}\in\mathrm{sp}(E,A)$ に対応する固有ベクトル鎖と呼ぶ. 無限大固有値に対する固有ベクトル鎖
$(v_{\infty j}^{1},v_{\infty j}^{2},\dots,v_{\infty j}^{k_{\infty j}})$,
$k\leq k_{\infty j}$, も同様に定義する. $\lambda=\infty$ を $i=\infty$ と読み替えれば
$\lambda\in\mathrm{sp}(E,A)\cup\{\infty\}$ を添字 $i=1,\dots,r,\infty$
を用いて統一的に扱うことができる. 次の定理では下付き添字を省略している. 
```{lemma}
\label{lem:28}任意の $k\in\mathbb{N}\cup\{0\}$ について, 
$$
\mathcal{G}_{\lambda}^{k}=\begin{cases}
V\ker(J-\lambda I)^{k} & \text{if}\quad\lambda\in\mathrm{sp}(E,A)\\
W\ker N^{k}=\mathcal{W}_{k} & \text{if}\quad\lambda=\infty
\end{cases}
$$
が成り立つ. 
```

```{proof}
定理 \ref{thm:quasi} により, 行列 $V\in\mathbb{F}^{n\times n_{1}}$, $W\in\mathbb{F}^{n\times n_{2}}$
が存在して $[V\ W]\in\mathbb{F}^{n\times n}$ は正則で
$$
AV=EVJ,\quad EW=AWN
$$
が成り立つことに注意する. 

\uline{まず $\lambda\in\mathrm{sp}(E,A)$ としよう}. $k=0$ のときは $\mathcal{G}_{\lambda}^{0}=\{0\}=V\ker(J-\lambda I)^{0}$
より明らか. ある $s$ について $\mathcal{G}_{\lambda}^{s}=V\ker(J-\lambda I)^{s}$
が成り立つとしよう. $v^{s+1}$, $v^{s}$ を
$$
v^{s+1}\in\mathcal{G}_{\lambda}^{s+1}\setminus\{0\},\qquad v^{s}\in\mathcal{G}_{\lambda}^{s},\quad\text{s.t.}\quad(A-\lambda E)v^{s+1}=Ev^{s}
$$
が成り立つように選ぶ. 命題 \ref{thm:22} (2) によって, $\xi_{1}\in\mathbb{F}^{n_{1}}$,
$\xi_{2}\in\mathbb{F}^{n_{2}}$ が一意的に存在して 
$$
v^{s+1}=V\xi_{1}+W\xi_{2}
$$
が成り立つことが分かる. 
$$
\begin{aligned}
(A-\lambda E)v^{s+1}=Ev^{s} & \Leftrightarrow(A-\lambda E)(V\xi_{1}+W\xi_{2})=Ev^{s}\\
 & \Leftrightarrow AV\xi_{1}+AW\xi_{2}-\lambda EV\xi_{1}-\lambda EW\xi_{2}=Ev^{s}\\
 & \Leftrightarrow EVJ\xi_{1}+AW\xi_{2}-\lambda EV\xi_{1}-\lambda AWN\xi_{2}=Ev^{s}\\
 & \Leftrightarrow EV(J\xi_{1}-\lambda I)\xi_{1}+AW(I-\lambda N)\xi_{2}=Ev^{s}\\
 & \Leftrightarrow AW(I-\lambda N)\xi_{2}=Ev^{s}+EV(\lambda I-J)\xi_{1}.
\end{aligned}
$$
帰納法の仮説より, $v^{s}\in\mathcal{G}_{\lambda}^{s}\subset V\ker(J-\lambda I)^{s}$
が成り立つ. さらに, $\mathrm{im}V=\mathcal{V}^{*}$ なので, 
$$
Ev^{s}\in E\mathcal{V}^{*},\quad EV(\lambda I-J)\xi_{1}\in E\mathcal{V}^{*}.
$$
したがって,
$$
W(I-\lambda N)\xi_{2}\in A^{-1}(E\mathcal{V}^{*})=\mathcal{V}^{*}.
$$
$\mathcal{W}^{*}=\mathrm{im}W$ なので, 実は
$$
W(I-\lambda N)\xi_{2}\in\mathcal{V}^{*}\cap\mathcal{W}^{*}=\{0\}.
$$
$W$ は単射なので, $(I-\lambda N)\xi_{2}=0$, すなわち, $\xi_{2}=\lambda N\xi_{2}$.
$N$ はべきゼロなので,
$$
\xi_{2}=\lambda N\xi_{2}=\lambda^{2}N^{2}\xi_{2}=\cdots=\lambda^{k^{*}}N^{k^{*}}\xi_{2}=0.
$$
一方, $v^{s}\in V\ker(J-\lambda I)^{s}$ としているので, ある $u\in\ker(J-\lambda I)^{s}$
が存在して, $v^{s}=Vu$ とできる. 
$$
\begin{aligned}
(A-\lambda E)v^{s+1}=Ev^{s} & \Rightarrow(A-\lambda E)v^{s+1}=EVu\\
 & \Rightarrow(A-\lambda E)V\xi_{1}=EVu\\
 & \Rightarrow EV(J-\lambda I)\xi_{1}=EVu,
\end{aligned}
$$
$EV$ は単射なので, $(J-\lambda I)\xi_{1}=u$. したがって, 
$$
v^{s+1}=V\xi_{1},\quad\xi_{1}\in\ker(J-\lambda I)^{s+1}
$$
が成り立つ. したがって, $\mathcal{G}_{\lambda}^{s+1}\subset V\ker(J-\lambda I)^{s+1}$
が成り立つ. 

逆の包含関係を示すために, $v^{s+1}\in\ker(J-\lambda I)^{s+1}$ としよう. $v^{s}\in\ker(J-\lambda I)^{s}$
を
$$
(J-\lambda I)v^{s+1}=v^{s}
$$
が成り立つように選ぶ. $EV$ は単射なので, これは
$$
EV(J-\lambda I)v^{s+1}=EVv^{s}
$$
と同値である. さらにこれは $EVJ=AV$ により
$$
(A-\lambda E)Vv^{s+1}=EVv^{s}
$$
 と同値. 帰納法の仮定 $\mathcal{G}_{\lambda}^{s}=V\ker(J-\lambda I)^{s}$ より,
$Vv^{s}\in\mathcal{G}_{\lambda}^{s}$ だから, 
$$
Vv^{s+1}\in\mathcal{G}_{\lambda}^{s+1}=(A-\lambda E)^{-1}\left(E\mathcal{G}_{\lambda}^{s}\right)
$$
が成り立つ. よって, $V\ker(J-\lambda I)^{s+1}\subset\mathcal{G}_{\lambda}^{s+1}$.
これで, 任意の $k$ について $\mathcal{G}_{\lambda}^{k}=V\ker(J-\lambda I)^{k}$
が示された. 

\uline{次に, $\lambda=\infty$ としよう}. まず, $\mathcal{G}_{\infty}^{k}=\mathcal{W}_{k}$
であることは2つの定義が一致していることから直ちに分かる. $\mathcal{G}_{\infty}^{k}=W\ker N^{k}$
を示す. $k=0$ に対しては自明である. ある $s$ について, $\mathcal{G}_{\infty}^{s}=W\ker N^{s}$
が成り立つと仮定する. $v^{s+1}\in\mathcal{G}_{\infty}^{s+1}\setminus\{0\}$
を任意に選ぶ. ある $v^{s}\in\mathcal{G}_{\infty}^{s}=W\ker N^{s}$ が存在して,
$$
Ev^{s+1}=Av^{s}
$$
が成り立つ. 帰納法の仮定より, $u\in\mathbb{F}^{n_{2}}$ が存在して $v^{s}=Wu$, $N^{s}u=0$
とできる. さらに, $v^{s+1}=V\xi_{1}+W\xi_{2}$ と分解すると, 
$$
EV\xi_{1}+EW\xi_{2}=AWu,\quad u\in\ker N^{s}
$$
を得る. $EW=AWN$ だから, 
$$
EV\xi_{1}=AW(u-N\xi_{2})
$$
あるいは
$$
\begin{bmatrix}EV & AW\end{bmatrix}\begin{bmatrix}\xi_{1}\\
u-N\xi_{2}
\end{bmatrix}=0.
$$
$[EV\ AW]$ は正則なので, $\xi_{1}=0$, $u=N\xi_{2}$. すなわち, 
$$
v^{s+1}=W\xi_{2},\quad\xi_{2}\in\ker N^{s+1}.
$$
これは, $v^{s+1}\in W\ker N^{s+1}$ を意味している. よって, $\mathcal{G}_{\lambda}^{s+1}\subset W\ker N^{s+1}$

次に, $v^{s+1}\in W\ker N^{s+1}$ としよう. このとき, ある $u\in\ker N^{s+1}$
が存在して
$$
v^{s+1}=Wu
$$
 とできる. $E$ は単射なので, これは次と同値.
$$
\begin{aligned}
Ev^{s+1} & =EWu\\
 & =AWNu.
\end{aligned}
$$
$Nu\in\ker N^{s}$ と $W\ker N^{s}=\mathcal{G}_{\infty}^{s}$ に注意すると,
$$
v^{s+1}\in E^{-1}\left(AW\ker N^{s}\right)=E^{-1}\left(A\mathcal{G}_{\infty}^{s}\right)=\mathcal{G}_{\infty}^{s+1}.
$$
よって, $W\ker N^{s+1}\subset\mathcal{G}_{\lambda}^{s+1}$. これで任意の $k$
について $\mathcal{G}_{\infty}^{k}=W\ker N^{k}$ が示された. 
```

補題 \ref{lem:28} と, $V$, $W$ の単射性が述べているのは, $(E,A)$ の固有空間の構造は, 通常の固有値問題に対する一般固有空間の構造を決定する方法と同様に決定できる.
したがって, 次の定理はジョルダン標準形の理論から導かれる. 
```{theorem, name='{Proposition 3.5, {[}BIT{]}}'}
ペンシル $(E,A)$ をレギュラーとする. 任意の $\lambda\in\mathrm{sp}(E,A)\cup\{\infty\}$
に対して, 次の 1〜5 が成り立つ. 

1. 任意の固有ベクトル鎖 $(v^{1},v^{2},\dots,v^{k})$ に対して, $v^{s}\in\mathcal{G}_{\lambda}^{s}\setminus\mathcal{G}_{\lambda}^{s-1}$,
$s=1,\dots,k$.
1. 任意の $k\le p(\lambda)$ と任意の $v\in\mathcal{G}_{\lambda}^{k}\setminus\mathcal{G}_{\lambda}^{k-1}$
に対して, $v^{k}=v$ なる固有ベクトル鎖 $(v^{1},\dots,v^{k})$ が一意的に存在する.
1. 任意の固有ベクトル鎖 $(v^{1},v^{2},\dots,v^{k})$ は1次独立である.
1. 次の包含関係が成り立つ
$$
\mathcal{G}_{\lambda}\subset\begin{cases}
\mathcal{V}^{*} & \text{if}\quad\lambda\in\mathrm{sp}(E,A)\\
\mathcal{W}^{*} & \text{if}\quad\lambda=\infty.
\end{cases}
$$
1. 任意の $\lambda\in\mathrm{sp}(E,A)\cup\{\infty\}$ に対して
$$
\dim\mathcal{G}_{\lambda}=\mathrm{am}(\lambda).
$$

```

%
```{proof}
省略する. 
```

%
ベクトル鎖の定義 $(A-\lambda E)v^{1}=Ev^{0}=0$, $(A-\lambda E)v^{s}=Ev^{s-1}$,
$v^{s}\in V\ker(J-\lambda I)^{s}$ より, $u^{s}\in\ker(J-\lambda I)^{s}$
が一意的に存在して $(A-\lambda E)Vu^{s}=EVu^{s-1}$ が成り立つ. $AV=EVJ$ より
$$
EV(J-\lambda I)u^{s}=EVu^{s-1}.
$$
$EV$ は単射なので, これは
$$
(J-\lambda I)u^{s}=u^{s-1}
$$
あるいは 
$$
Ju^{s}=\lambda u^{s}+u^{s-1}
$$
と同値である. したがって, 
$$
J[u^{1}\ \cdots\ u^{k}]=[u^{1}\ \cdots\ u^{k}]\begin{bmatrix}\lambda & 1\\
 & \lambda & \ddots\\
 &  & \ddots & 1\\
 &  &  & \lambda
\end{bmatrix}.
$$
両辺に左から $EV$ を掛けると, 
$$
A[Vu^{1}\ \cdots\ Vu^{k}]=[EVu^{1}\ \cdots\ EVu^{k}]\begin{bmatrix}\lambda & 1\\
 & \lambda & \ddots\\
 &  & \ddots & 1\\
 &  &  & \lambda
\end{bmatrix},
$$
したがって
$$
A[v^{1}\ \cdots\ v^{k}]=[Ev^{1}\ \cdots\ Ev^{k}]\begin{bmatrix}\lambda & 1\\
 & \lambda & \ddots\\
 &  & \ddots & 1\\
 &  &  & \lambda
\end{bmatrix}
$$
が成り立つ. これは (\ref{eq:weier_a}) ですでに得たワイエルシュトラス正準形と一致する. 同様に, $E$
の変換を考える. ベクトル鎖の定義 $Ew^{1}=Aw^{0}=0$, $Ew^{s}=Aw^{s-1}$, $w^{s}\in W\ker N^{s}$
より, $u^{s}\in\ker N^{s}$ が一意的に存在して $EWu^{s}=AWu^{s-1}$ が成り立つ. $EW=AWN$
により, 
$$
AW(Nu^{s}-u^{s-1})=0.
$$
$AW$ は単射なので, これは
$$
Nu^{s}-u^{s-1}=0
$$
と同値である. $N$ の $[u^{1}\ \cdots\ u^{k}]$ に関する次の行列表現を得る.
$$
N[u^{1}\ \cdots\ u^{k}]=[u^{1}\ \cdots\ u^{k}]\begin{bmatrix}0 & 1\\
 & 0 & \ddots\\
 &  & \ddots & 1\\
 &  &  & 0
\end{bmatrix}.
$$
両辺に左から $AW$ を掛けると, 
$$
AWN[u^{1}\ \cdots\ u^{k}]=AW[u^{1}\ \cdots\ u^{k}]\begin{bmatrix}0 & 1\\
 & 0 & \ddots\\
 &  & \ddots & 1\\
 &  &  & 0
\end{bmatrix}.
$$
あるいは, 
$$
E[Wu^{1}\ \cdots\ Wu^{k}]=[AWu^{1}\ \cdots\ AWu^{k}]\begin{bmatrix}0 & 1\\
 & 0 & \ddots\\
 &  & \ddots & 1\\
 &  &  & 0
\end{bmatrix}.
$$
したがって, 
$$
E[w^{1}\ \cdots\ w^{k}]=[Aw^{1}\ \cdots\ Aw^{k}]\begin{bmatrix}0 & 1\\
 & 0 & \ddots\\
 &  & \ddots & 1\\
 &  &  & 0
\end{bmatrix}
$$
を得る. これは式 (\ref{eq:weier_e}) と一致する. 
```{theorem}
\label{thm:dec}$(E,A)$ をレギュラーとする. 任意の $i=1,\dots,r$ と任意の $j=1,\dots,\eta_{i}=\mathrm{gm}(\lambda_{i})$
について, ある $1\le k_{ij}\le p(\lambda_{i})$ と固有ベクトル鎖 $V_{ij}:=\left[v_{ij}^{1}\ v_{ij}^{2}\ \cdots\ v_{ij}^{k_{ij}}\right]$
が存在して, 
$$
\mathcal{G}_{\lambda_{i}}=\bigoplus_{j=1}^{\mu_{i}}\mathrm{im}V_{ij}
$$
が成り立つ. さらに
$$
\begin{aligned}
\mathcal{V}^{*} & =\bigoplus_{i=1}^{r}\mathcal{G}_{\lambda_{i}},\\
\mathcal{W}^{*} & =\mathcal{G}_{\infty}
\end{aligned}
$$
が成り立つ. 
```

```{proof}
$\lambda,\mu\in\mathrm{sp}(E,A)$, $\lambda\neq\mu$ に対して $\mathcal{G}_{\lambda}\cap\mathcal{G}_{\mu}=\{0\}$
であることを示そう. $v\neq0$ が
$$
v\in\mathcal{G}_{\lambda}\cap\mathcal{G}_{\mu}
$$
を満たすとしよう. 補題 \ref{lem:28} から
$$
\begin{aligned}
v & \in\mathcal{G}_{\lambda}=V\ker(J-\lambda I)^{p(\lambda)}\\
v & \in\mathcal{G}_{\mu}=V\ker(J-\mu I)^{p(\mu)}
\end{aligned}
$$
が成り立つ. $V:\mathbb{F}^{n_{1}}\to\mathbb{F}^{n}$ は単射なので,
$$
\begin{aligned}
\dim\ker(J-\lambda I)^{p(\lambda)} & =\dim\mathcal{G}_{\lambda}=\mathrm{am}(\lambda)\\
\dim\ker(J-\mu I)^{p(\mu)} & =\dim\mathcal{G}_{\mu}=\mathrm{am}(\mu).
\end{aligned}
$$
したがって, $J$ の最小多項式が $(z-\lambda)^{p(\lambda)}$ と $(z-\mu)^{p(\mu)}$
を因数として持つことを表している. $J$ に対するハミルトン・ケーリーの定理より
$$
\ker(J-\lambda I)^{p(\lambda)}\cap\ker(J-\mu I)^{p(\mu)}=\{0\}
$$
が従うので, $v=0$ でなければならない. 
```

定理 \ref{thm:dec} で構成したベクトル鎖を並べたもの
$$
\bar{V}=\left[v_{ij}^{1},\dots,v_{ij}^{k_{ij}}\ \mid\ i=1,\dots,r,\ j=1,\dots,\eta_{i}\right]
$$
は $\mathcal{V}^{*}$ の基底をなす. また, 
$$
\bar{W}=\left[v_{\infty j}^{1},\dots,v_{\infty j}^{k_{\infty j}}\ \mid\ j=1,\dots,\eta\right]
$$
は $\mathcal{W}^{*}$ の基底をなす. これで定理 \ref{thm:weier} の証明が完了する. 

\bibliographystyle{ecta}
\bibliography{16ED}

